import type { StaticDrill } from './types';

// Static drills for Part A (Common core). Every item is grounded in the guide's text,
// worked examples and COMMON TRAPS boxes.
export const CORE_DRILLS: StaticDrill[] = [
  // CORE-01 Income statement
  { id: 'c01a', topic: 'CORE-01', kind: 'mcq', q: 'Kaveri FY26: revenue 2,000; COGS 1,100; employee benefits 160; other expenses 340. What is the EBITDA margin?', options: ['20.0%', '45.0%', '16.0%', '24.0%'], answer: 0, why: 'EBITDA = 2,000 − 1,100 − 160 − 340 = 400, so the margin is 400 ÷ 2,000 = 20.0%. 45% is the gross margin and 16% is the EBIT margin after D&A of 80.', tags: [null, 'concept', 'concept', 'arithmetic'] },
  { id: 'c01b', topic: 'CORE-01', kind: 'order', q: 'Put the subtotals in the order you read them down the income statement.', items: ['Revenue from operations', 'Gross profit', 'EBITDA', 'EBIT', 'Profit before tax', 'Profit after tax'], why: 'Each subtotal answers a different question: product economics (gross profit), cost structure before capital intensity and financing (EBITDA), earnings for all capital providers (EBIT), then PBT and PAT for shareholders.' },
  { id: 'c01c', topic: 'CORE-01', kind: 'mcq', q: 'A cash-rich FMCG company reports large other income (treasury income, dividends). How should it enter EBITDA?', options: ['Keep it out of EBITDA; it is not operating', 'Add it to revenue from operations', 'Include it in EBITDA because it is recurring', 'Deduct it from finance costs'], answer: 0, why: 'Other income is not operating. Keep it out of EBITDA. It can be large for cash-rich IT services and FMCG companies.', tags: [null, 'concept', 'concept', 'concept'] },
  { id: 'c01d', topic: 'CORE-01', kind: 'mcq', q: 'Why is EV/EBITDA the default valuation multiple?', options: ['EBITDA strips out capital intensity (D&A) and financing (interest), so companies with different asset bases and capital structures compare', 'EBITDA equals operating cash flow', 'EBITDA is audited while PAT is not', 'EBITDA includes other income, so it is complete'], answer: 0, why: 'EBITDA removes D&A and financing, which makes companies comparable. It is not cash flow: it ignores working capital, capex, interest and tax.', tags: [null, 'concept', 'concept', 'concept'] },
  { id: 'c01e', topic: 'CORE-01', kind: 'mcq', q: 'A company tags the same "restructuring" charge as exceptional every year. What should an analyst do?', options: ['Read the note and treat recurring items as operating when normalising profit', 'Always add exceptional items back to EBITDA', 'Ignore the line because it sits below EBITDA', 'Subtract it twice to be conservative'], answer: 0, why: 'Exceptional items sit on a separate line before PBT. Some companies label recurring costs as exceptional to flatter "adjusted" profit, so read the note and ask whether they recur.' },
  { id: 'c01f', topic: 'CORE-01', kind: 'mcq', q: 'Which profit line does valuation work almost always use?', options: ['Profit after tax (PAT)', 'Total comprehensive income', 'Profit before tax plus other comprehensive income', 'Gross profit'], answer: 0, why: 'Below PAT sit other comprehensive income items (actuarial gains, some fair value changes, FX on foreign operations). Valuation uses PAT, not total comprehensive income.' },

  // CORE-02 Balance sheet
  { id: 'c02a', topic: 'CORE-02', kind: 'sort', q: 'Group these balance sheet lines by what they do.', buckets: ['Operating', 'Financing', 'Non-operating'], items: [['PP&E', 0], ['Inventory', 0], ['Trade receivables', 0], ['Trade payables', 0], ['Provisions', 0], ['Borrowings', 1], ['Lease liabilities', 1], ['Cash', 1], ['Preference capital', 1], ['Investment in associates', 2], ['Surplus land', 2]], why: 'Operating items generate the business\'s returns. Financing items drive net debt and the equity bridge. Non-operating assets are valued separately.' },
  { id: 'c02b', topic: 'CORE-02', kind: 'mcq', q: "Kaveri's equity rose from 735 to 900 in FY26. Which flows explain the change?", options: ['PAT of 225 added, dividends of 60 paid', 'PAT of 165 added', 'New shares of 165 issued', 'Revaluation of PP&E by 165'], answer: 0, why: 'Every flow explains a change in a stock: 735 + 225 − 60 = 900.' },
  { id: 'c02c', topic: 'CORE-02', kind: 'mcq', q: 'The balance sheet shows:', options: ['Stocks (balances) at a point in time', 'Flows during the year', 'Only cash movements', 'Profit for the period'], answer: 0, why: 'The balance sheet is a snapshot. The income statement and cash flow statement show flows during the year.' },
  { id: 'c02d', topic: 'CORE-02', kind: 'mcq', q: 'Kaveri FY26: PP&E 950, goodwill 100, inventory 220, receivables 160, cash 150. What are total assets?', options: ['1,580', '1,480', '1,425', '1,430'], answer: 0, why: '950 + 100 + 220 + 160 + 150 = 1,580, which equals payables 200 + other current liabilities 80 + borrowings 400 + equity 900.' },

  // CORE-03 Cash flow statement
  { id: 'c03a', topic: 'CORE-03', kind: 'sort', q: 'Which section of the cash flow statement does each item sit in?', buckets: ['Operating (CFO)', 'Investing (CFI)', 'Financing (CFF)'], items: [['Increase in receivables', 0], ['Depreciation add-back', 0], ['Capital expenditure', 1], ['Acquisition of a business', 1], ['Purchase of investments', 1], ['Dividends paid', 2], ['Borrowings repaid', 2], ['Equity issued', 2], ['Lease principal', 2]], why: 'CFO is cash from running the business; CFI is capex, acquisitions and investments; CFF is debt, equity, dividends, buybacks and lease principal.' },
  { id: 'c03b', topic: 'CORE-03', kind: 'mcq', q: 'Kaveri FY26: CFO 280, capex 150, PAT 225. What are free cash flow and cash conversion?', options: ['FCF 130; cash conversion 1.24x', 'FCF 75; cash conversion 0.80x', 'FCF 130; cash conversion 0.58x', 'FCF 280; cash conversion 1.24x'], answer: 0, why: 'FCF = CFO − capex = 130. Cash conversion = CFO ÷ PAT = 280 ÷ 225 = 1.24x, normal for a company with meaningful D&A.' },
  { id: 'c03c', topic: 'CORE-03', kind: 'mcq', q: 'Under Ind AS 7, where do Indian companies usually classify interest paid?', options: ['Financing activities', 'Operating activities, always', 'Investing activities', 'It is not shown'], answer: 0, why: 'Indian companies usually start the indirect method from PBT, show taxes paid as an operating line and classify interest paid under financing. Check where interest and lease payments sit before comparing CFO.' },
  { id: 'c03d', topic: 'CORE-03', kind: 'mcq', q: 'True or false: "EBITDA is cash flow."', options: ['False: it ignores working capital, capex, interest and tax', 'True for most companies', 'True if there is no debt', 'True under Ind AS'], answer: 0, why: 'A fast-growing distributor can have strong EBITDA and negative operating cash flow.', tags: [null, 'concept', 'concept', 'concept'] },

  // CORE-04 Three-statement links
  { id: 'c04a', topic: 'CORE-04', kind: 'mcq', q: 'A company buys inventory of Rs. 100 on credit. What happens?', options: ['No P&L effect; inventory +100 and payables +100; cash unchanged', 'Expense of 100; cash −100', 'Inventory +100; cash −100', 'Revenue +100; payables +100'], answer: 0, why: 'On the cash flow statement the inventory increase (−100) and payables increase (+100) offset.', tags: [null, 'concept', 'wc_sign', 'concept'] },
  { id: 'c04b', topic: 'CORE-04', kind: 'mcq', q: 'The company then sells that inventory for Rs. 150 cash. Tax is 25%. What is the change in cash?', options: ['+137.5', '+150', '+37.5', '+112.5'], answer: 0, why: 'Revenue +150, COGS +100, PBT +50, tax 12.5, NI +37.5. CFO = NI 37.5 + inventory decrease 100 = 137.5 (the customer paid 150 and tax took 12.5).', tags: [null, 'forgot_tax', 'wc_sign', 'concept'] },
  { id: 'c04c', topic: 'CORE-04', kind: 'mcq', q: 'A customer prepays Rs. 120 for a one-year subscription. What happens at receipt?', options: ['No revenue; cash +120 in CFO; deferred revenue liability +120', 'Revenue +120; cash +120', 'Revenue +10; cash +10', 'Receivable +120; revenue +120'], answer: 0, why: 'Cash arrives before delivery, so it is a liability. Each month revenue of 10 is recognised and the liability falls by 10.' },
  { id: 'c04d', topic: 'CORE-04', kind: 'mcq', q: 'Raise Rs. 100 of debt at 10% and buy a machine depreciated at 10 a year. Tax 25%. What is the change in year-1 net income?', options: ['−15', '−20', '−10', '−7.5'], answer: 0, why: 'Interest 10 and depreciation 10 reduce PBT by 20; after 25% tax, NI falls by 15. Day one had no P&L effect: CFF +100, CFI −100.', tags: [null, 'forgot_tax', 'concept', 'concept'] },
  { id: 'c04e', topic: 'CORE-04', kind: 'mcq', q: 'Goodwill is impaired by Rs. 50 and the impairment is not tax-deductible. What is the cash effect?', options: ['None: CFO adds back the 50', 'Cash falls by 50', 'Cash falls by 37.5', 'Cash rises by 12.5'], answer: 0, why: 'PBT −50 and NI −50 (no tax saving). CFO adds back the non-cash 50. Goodwill −50, equity −50. State your tax assumption either way.' },
  { id: 'c04f', topic: 'CORE-04', kind: 'mcq', q: 'Where does interest expense go?', options: ['The income statement; debt principal repayment is financing cash flow', 'Only the balance sheet', 'Investing cash flow', 'Equity'], answer: 0, why: 'Putting interest in the wrong place is a common trap. Interest hits the income statement; repaying principal does not.', tags: [null, 'concept', 'concept', 'concept'] },

  // CORE-05 Accruals and revenue recognition
  { id: 'c05a', topic: 'CORE-05', kind: 'order', q: 'Order the five steps of Ind AS 115.', items: ['Identify the contract with the customer', 'Identify the performance obligations', 'Determine the transaction price', 'Allocate the price to each obligation', 'Recognise revenue when (or as) each obligation is satisfied'], why: 'Variable consideration enters at step 3; standalone selling prices drive step 4; step 5 is at a point in time or over time.' },
  { id: 'c05b', topic: 'CORE-05', kind: 'sort', q: 'Where does each item sit on the balance sheet?', buckets: ['Current asset', 'Liability'], items: [['Accrued revenue (unbilled)', 0], ['Trade receivable', 0], ['Prepaid expense', 0], ['Inventory', 0], ['Deferred revenue', 1], ['Accrued expense', 1]], why: 'Accrual accounting records revenue when earned and expenses when incurred. The timing gap is what working capital measures.' },
  { id: 'c05c', topic: 'CORE-05', kind: 'mcq', q: 'A phone is sold with a two-year service plan. How many performance obligations?', options: ['Two', 'One', 'Twenty-four', 'None until the plan ends'], answer: 0, why: 'They are distinct promises, so the price is allocated between them using standalone selling prices.' },
  { id: 'c05d', topic: 'CORE-05', kind: 'mcq', q: 'An e-commerce platform acts as agent for third-party sellers. What should it book as revenue?', options: ['Only its commission', 'The full gross merchandise value', 'GMV less returns', 'Nothing until the seller is paid'], answer: 0, why: 'Principal-versus-agent judgements are a classic place where revenue is inflated.' },
  { id: 'c05e', topic: 'CORE-05', kind: 'mcq', q: 'A distributor holds 60 days of stock, gives 90 days of credit and pays suppliers in 30 days. Roughly how much working capital does each extra Rs. 100 of annual sales tie up?', options: ['About Rs. 33', 'About Rs. 16', 'About Rs. 50', 'About Rs. 8'], answer: 0, why: '100 × (60 + 90 − 30) ÷ 365 ≈ 33. Profitable growth can consume more cash than it produces, which is how a profitable company runs out of cash.' },

  // CORE-06 Working capital
  { id: 'c06a', topic: 'CORE-06', kind: 'mcq', q: 'Kaveri: receivables 160, inventory 220, payables 200, other current liabilities 80. What is net working capital?', options: ['100', '180', '380', '530'], answer: 0, why: 'NWC = operating current assets − operating current liabilities = 160 + 220 − 200 − 80 = 100. Cash and debt are excluded as financing items.' },
  { id: 'c06b', topic: 'CORE-06', kind: 'mcq', q: 'What is the difference between the operating cycle and the cash conversion cycle?', options: ['The CCC subtracts DPO, the part suppliers finance', 'The CCC adds DPO', 'They are the same', 'The operating cycle excludes inventory'], answer: 0, why: 'Operating cycle = DIO + DSO. CCC = DIO + DSO − DPO. A negative CCC funds growth.' },
  { id: 'c06c', topic: 'CORE-06', kind: 'sort', q: 'Typical working capital profile by business type.', buckets: ['Low or negative', 'High', 'Moderate (high DSO)'], items: [['Branded FMCG, organised retail', 0], ['Quick commerce and marketplaces', 0], ['Capital goods, EPC contractors', 1], ['Pharma exporters, chemicals', 1], ['IT services', 2]], why: 'FMCG pays suppliers after goods sell; marketplaces collect first and pay sellers later; EPC has long cycles and retention money; IT invoices in arrears.' },
  { id: 'c06d', topic: 'CORE-06', kind: 'mcq', q: 'A sudden rise in DSO is often the first sign of:', options: ['Channel stuffing or customer stress', 'Better collections', 'Lower inventory', 'Higher supplier credit'], answer: 0, why: 'Receivables up means customers have not paid you yet.' },

  // CORE-07 D&A, impairment, goodwill, intangibles, leases, SBP
  { id: 'c07a', topic: 'CORE-07', kind: 'mcq', q: 'Under Ind AS 36, recoverable amount is:', options: ['The higher of fair value less costs of disposal and value in use', 'The lower of cost and market', 'Book value less depreciation', 'Market capitalisation'], answer: 0, why: 'If carrying amount exceeds recoverable amount, the asset is written down. Goodwill and indefinite-life intangibles are tested every year.' },
  { id: 'c07b', topic: 'CORE-07', kind: 'mcq', q: 'An acquired brand is judged to have an indefinite life. How is it treated under Ind AS 38?', options: ['Not amortised; tested for impairment every year', 'Amortised over 10 years', 'Expensed immediately', 'Added to goodwill and amortised'], answer: 0, why: 'Customer lists and technology bought in an acquisition are amortised. Indefinite-life brands are only tested for impairment. Internally generated brands are not recognised at all.' },
  { id: 'c07c', topic: 'CORE-07', kind: 'mcq', q: 'A company starts capitalising development costs it used to expense. What happens to EBITDA?', options: ['It rises today; depreciation or amortisation rises later', 'It falls today', 'No effect', 'It rises permanently with no later cost'], answer: 0, why: 'Rising capitalised costs with flat revenue is a warning sign.' },
  { id: 'c07d', topic: 'CORE-07', kind: 'mcq', q: 'You compare airlines on post-Ind AS 116 EBITDA (rent removed). What must EV include?', options: ['Lease liabilities', 'Nothing extra', 'Only aircraft owned', 'Deferred revenue'], answer: 0, why: 'Keep the bridge consistent: if EBITDA excludes rent, EV must include lease liabilities. Or compare on EBITDAR.', tags: [null, 'concept', 'concept', 'concept'] },
  { id: 'c07e', topic: 'CORE-07', kind: 'mcq', q: 'A new-age company reports "adjusted EBITDA excluding ESOP cost". Your view?', options: ['Be sceptical: ESOPs are a real transfer of value; use diluted shares', 'Accept it: ESOPs are non-cash', 'Add ESOPs back to PAT too', 'Treat ESOPs as debt'], answer: 0, why: 'ESOP cost is non-cash but real.' },

  // CORE-08 Group accounts
  { id: 'c08a', topic: 'CORE-08', kind: 'sort', q: 'How is each holding accounted for?', buckets: ['Full consolidation', 'Equity method', 'Financial asset at fair value'], items: [['70% subsidiary (control)', 0], ['50:50 joint venture (joint control)', 1], ['30% associate (significant influence)', 1], ['10% stake, no influence', 2]], why: 'Control → Ind AS 110; joint control and significant influence → equity method (Ind AS 111, 28); below 20% with no influence → Ind AS 109.' },
  { id: 'c08b', topic: 'CORE-08', kind: 'mcq', q: 'In the EV bridge, what do you do with investments in associates?', options: ['Subtract them: their EBITDA is not in yours', 'Add them', 'Ignore them', 'Add their EBITDA to yours'], answer: 0, why: 'Add NCI because consolidated EBITDA includes 100% of subsidiaries; subtract associates and JVs because their earnings sit below EBITDA.', tags: [null, 'nci_sign', 'concept', 'concept'] },
  { id: 'c08c', topic: 'CORE-08', kind: 'mcq', q: 'Tax depreciation is faster than book depreciation. What does this create?', options: ['A deferred tax liability', 'A deferred tax asset', 'A current tax refund', 'Goodwill'], answer: 0, why: 'Tax is deferred to later years. Carry-forward losses create deferred tax assets, recognised only if future taxable profit is probable.' },
  { id: 'c08d', topic: 'CORE-08', kind: 'mcq', q: 'You strip a one-off restructuring cost out of normalised profit. What else must you do?', options: ['Strip one-off gains too, and check whether "one-offs" recur', 'Nothing', 'Add back all exceptional items forever', 'Use total comprehensive income'], answer: 0, why: 'Be consistent when normalising.' },

  // CORE-09 Annual report
  { id: 'c09a', topic: 'CORE-09', kind: 'mcq', q: 'Which part of an Indian annual report should you read first?', options: ['The audit report', 'The chairman\'s letter', 'The CSR report', 'The notice of AGM'], answer: 0, why: 'An unmodified opinion is the norm. Also read Key Audit Matters, any Emphasis of Matter and the CARO 2020 annexure.' },
  { id: 'c09b', topic: 'CORE-09', kind: 'sort', q: 'Which audit outcomes are serious?', buckets: ['The norm', 'Serious'], items: [['Unmodified opinion', 0], ['Qualified opinion', 1], ['Adverse opinion', 1], ['Disclaimer of opinion', 1], ['Auditor resignation mid-term', 1]], why: 'SEBI LODR requires the reasons for a mid-term auditor resignation to be disclosed.' },
  { id: 'c09c', topic: 'CORE-09', kind: 'mcq', q: 'Under the Ind AS carve-out, a bargain purchase gain goes to:', options: ['Capital reserve', 'Profit and loss', 'Goodwill', 'Revenue'], answer: 0, why: 'Other carve-outs: Schedule III presentation, and pooling of interests for common-control combinations.' },
  { id: 'c09d', topic: 'CORE-09', kind: 'mcq', q: 'Material related party transactions need shareholder approval under:', options: ['SEBI LODR Regulation 23', 'Ind AS 108', 'CARO 2020', 'The Takeover Regulations'], answer: 0, why: 'Read the related party note: loans, royalties and purchases with promoter entities.' },

  // CORE-10 Margins, growth and returns
  { id: 'c10a', topic: 'CORE-10', kind: 'mcq', q: "Kaveri: PAT 225, revenue 2,000, assets 1,580, equity 900. What is the equity multiplier in the DuPont split?", options: ['1.76x', '1.27x', '11.25%', '25.0%'], answer: 0, why: 'ROE 25% = margin 11.25% × asset turnover 1.27x × equity multiplier 1.76x (1,580 ÷ 900).' },
  { id: 'c10b', topic: 'CORE-10', kind: 'mcq', q: 'Company B has Rs. 1,000 crore of capital, 9% ROIC and a 12% cost of capital. What is its economic profit?', options: ['−Rs. 30 crore a year', '+Rs. 90 crore a year', '+Rs. 30 crore a year', 'Zero'], answer: 0, why: '(9% − 12%) × 1,000 = −30. Growing capital at the same ROIC grows the economic loss.' },
  { id: 'c10c', topic: 'CORE-10', kind: 'mcq', q: '"High sales growth but low ROCE, or slow growth but high ROCE?" The strong answer:', options: ['Prefer high ROCE unless the low-ROCE company is in a temporary investment phase with rising incremental returns', 'Always prefer growth', 'Always prefer the cheaper stock', 'They are equivalent'], answer: 0, why: 'Growth at ROIC above WACC creates value; below WACC it destroys it faster.' },
  { id: 'c10d', topic: 'CORE-10', kind: 'mcq', q: 'How does a large expansion affect ROCE in the short run?', options: ['It falls: capital rises now, earnings arrive as utilisation ramps', 'It rises immediately', 'No effect', 'It depends only on tax'], answer: 0, why: 'Judge expansions on incremental ROCE at maturity.' },
  { id: 'c10e', topic: 'CORE-10', kind: 'mcq', q: 'Which ratio misleads when the balance sheet uses old, depreciated assets?', options: ['ROCE (it looks inflated)', 'Current ratio', 'P/E', 'DSO'], answer: 0, why: 'Old depreciated assets shrink capital employed. Leverage inflates ROE.' },

  // CORE-11 Unit economics
  { id: 'c11a', topic: 'CORE-11', kind: 'mcq', q: 'LTV should be calculated on:', options: ['Contribution or gross profit per period', 'Revenue per period', 'EBITDA of the company', 'CAC'], answer: 0, why: 'Calculating LTV on revenue is the first trap in the guide.', tags: [null, 'ltv_on_revenue', 'concept', 'concept'] },
  { id: 'c11b', topic: 'CORE-11', kind: 'mcq', q: 'Why is blended CAC misleading?', options: ['It includes organic, free customers, which makes paid acquisition look cheap', 'It excludes marketing', 'It uses gross profit', 'It is always too high'], answer: 0, why: 'Measure paid CAC separately.' },
  { id: 'c11c', topic: 'CORE-11', kind: 'mcq', q: 'What LTV/CAC is the rule of thumb for a healthy subscription business?', options: ['Above 3x', 'Above 1x', 'Above 10x', 'Below 1x'], answer: 0, why: 'The clinic startup at 2.2x should cut churn or CAC before scaling spend.' },
  { id: 'c11d', topic: 'CORE-11', kind: 'mcq', q: 'In a cohort retention heatmap, how do you read improvement?', options: ['Down a column: newer cohorts retain better at the same age', 'Across a row only', 'Only the last column', 'By the average of all cells'], answer: 0, why: 'Read across a row for decay and down a column for improvement. Averages hide whether newer cohorts are better.' },
  { id: 'c11e', topic: 'CORE-11', kind: 'mcq', q: 'For a cement company, which unit metric do you compare across peers?', options: ['EBITDA per tonne', 'Revenue per employee', 'DAU/MAU', 'GMV'], answer: 0, why: 'Explain the gap with limestone proximity, fuel mix and logistics.' },

  // CORE-12 Revenue drivers
  { id: 'c12a', topic: 'CORE-12', kind: 'sort', q: 'Match each business to the revenue decomposition the guide uses.', buckets: ['Volume and price', 'Customers and ARPU', 'Capacity and utilisation', 'Channel'], items: [['Cement: tonnes × Rs. per tonne', 0], ['Telecom: subscribers × ARPU', 1], ['Hotels: rooms × occupancy × ADR', 2], ['FMCG: modern trade, general trade, e-commerce', 3]], why: 'Choose the decomposition that matches how the company reports and runs itself.' },
  { id: 'c12b', topic: 'CORE-12', kind: 'order', q: 'Order the steps for projecting revenue in an interview or pitch.', items: ['Start from how the company reports', 'Pick the two or three drivers that explain most of the history', 'Tie each driver to an external anchor', 'Triangulate bottom-up with top-down and consensus', "Sanity-check against the company's own history"], why: 'If you forecast faster growth than the company has ever achieved, say why.' },
  { id: 'c12c', topic: 'CORE-12', kind: 'sort', q: 'Classify each cost by behaviour.', buckets: ['Variable', 'Semi-variable', 'Fixed'], items: [['Raw materials', 0], ['Freight', 0], ['Sales commissions', 0], ['Power', 1], ['Some labour', 1], ['Rent', 2], ['Head office salaries', 2], ['Depreciation', 2]], why: 'The mix determines operating leverage: high fixed costs make profit swing more than revenue.' },

  // CORE-13 Quality of earnings
  { id: 'c13a', topic: 'CORE-13', kind: 'multi', q: 'Select every red flag.', options: ['Receivables growing much faster than revenue', 'CFO persistently below PAT', 'Recurring revenue from many customers', 'High cash and high borrowing at the same time', 'Rising promoter share pledges', 'Other income forming a big share of profit', 'A normal tax rate'], answers: [0, 1, 3, 4, 5], why: 'Signs of high quality include recurring revenue from many customers and a normal tax rate. The others are red flags from A2.4.' },
  { id: 'c13b', topic: 'CORE-13', kind: 'mcq', q: 'A company capitalises Rs. 50 of costs it used to expense. What happens this year?', options: ['EBITDA +50; CFO +50, CFI −50; total cash unchanged', 'EBITDA −50; cash −50', 'No effect on EBITDA', 'Cash +50'], answer: 0, why: 'Later years carry the depreciation or amortisation. Rising capitalisation with flat revenue is a quality-of-earnings red flag.' },
  { id: 'c13c', topic: 'CORE-13', kind: 'mcq', q: 'Receivables grew twice as fast as revenue. What do you check first?', options: ['Credit terms, customer concentration and ageing, period-end channel stuffing, policy changes, related party sales', 'The tax rate', 'The dividend history', 'The share price'], answer: 0, why: 'Then look for the effect on operating cash flow.' },

  // CORE-14 Time value, NPV, IRR
  { id: 'c14a', topic: 'CORE-14', kind: 'mcq', q: 'For mutually exclusive projects, which rule decides?', options: ['NPV at the correct cost of capital', 'The higher IRR', 'The shorter payback', 'The higher profitability index'], answer: 0, why: 'IRR can mis-rank projects of different scale or timing and can have multiple solutions.', tags: [null, 'concept', 'concept', 'concept'] },
  { id: 'c14b', topic: 'CORE-14', kind: 'mcq', q: 'Project A (10, 20, 30, 70, 90) has IRR 23.0%; Project B (60, 50, 30, 10, 5) has IRR 25.8%. Each costs 100. At a 10% cost of capital, which creates more value?', options: ['A (NPV 51.9 versus 28.3)', 'B, because its IRR is higher', 'They are equal', 'Neither'], answer: 0, why: 'The NPV profiles cross at 20.4%: below that rate A wins, above it B wins.' },
  { id: 'c14c', topic: 'CORE-14', kind: 'mcq', q: "What does Excel's NPV function assume?", options: ['The first cash flow arrives one period from now', 'The first cash flow is today', 'Dated cash flows', 'Continuous compounding'], answer: 0, why: 'Use XNPV and XIRR for dated cash flows, which is what real deals use.' },
  { id: 'c14d', topic: 'CORE-14', kind: 'mcq', q: 'Why might a PE fund care about IRR while a CFO cares about NPV?', options: ['LPs judge funds on IRR and multiple over a limited life; a company with ongoing access to capital maximises rupee value', 'NPV is illegal for funds', 'IRR ignores timing', 'CFOs cannot compute IRR'], answer: 0, why: 'Funds also track MOIC because a high IRR on a quick flip may return little money.' },
  { id: 'c14e', topic: 'CORE-14', kind: 'mcq', q: "What is the profitability index's main weakness?", options: ['It ignores project size, so it can mis-rank mutually exclusive projects', 'It ignores time value', 'It needs no discount rate', 'It double counts cash'], answer: 0, why: 'PI ranks projects under capital rationing. NPV measures value in rupees.' },

  // CORE-15 Cost of capital
  { id: 'c15a', topic: 'CORE-15', kind: 'mcq', q: 'Which weights belong in WACC?', options: ['Target market-value weights', 'Book value weights', 'The current (temporary) capital structure', 'Equal weights'], answer: 0, why: 'Using book weights or a temporary structure is a trap.', tags: [null, 'concept', 'concept', 'concept'] },
  { id: 'c15b', topic: 'CORE-15', kind: 'mcq', q: 'Which cost of debt goes into WACC?', options: ['The marginal pre-tax rate on new debt, then taxed once', 'The historical average coupon', 'The after-tax rate, taxed again in the formula', 'The risk-free rate'], answer: 0, why: 'WACC = E/V × Ke + D/V × Kd × (1 − t), with Kd pre-tax.', tags: [null, 'concept', 'taxed_twice', 'concept'] },
  { id: 'c15c', topic: 'CORE-15', kind: 'mcq', q: 'You value an acquisition target. Whose risk sets the discount rate?', options: ["The target's", "The acquirer's WACC", 'The market average', 'The lowest available'], answer: 0, why: "Using the acquirer's WACC to value a target is a named trap." },
  { id: 'c15d', topic: 'CORE-15', kind: 'mcq', q: "A raw regression beta is 1.3. What is Bloomberg's adjusted beta?", options: ['1.20', '1.30', '0.87', '1.00'], answer: 0, why: '0.67 × 1.3 + 0.33 × 1 = 1.201, pulled towards 1.' },
  { id: 'c15e', topic: 'CORE-15', kind: 'mcq', q: 'Why can adding a full country risk premium to a rupee risk-free rate double count?', options: ['The G-sec yield already includes part of India\'s default spread', 'CRP is always zero for India', 'ERP excludes India', 'Beta already includes CRP'], answer: 0, why: 'Be consistent. Damodaran\'s January 2026 India ERP is 7.08% (4.23% mature plus 2.85% CRP).' },
  { id: 'c15f', topic: 'CORE-15', kind: 'mcq', q: 'Does WACC keep falling as debt rises?', options: ['No: more debt raises the cost of equity, and distress costs eventually outweigh the tax shield', 'Yes, always', 'Yes, until debt is 100%', 'It is unaffected by debt'], answer: 0, why: 'The trade-off gives an optimal range, not a point.' },

  // CORE-16 Sensitivity
  { id: 'c16a', topic: 'CORE-16', kind: 'mcq', q: 'What does a tornado chart do?', options: ['Ranks inputs by their impact on the answer', 'Shows a base case only', 'Forecasts revenue', 'Plots NPV against IRR'], answer: 0, why: 'For the Rs. 120 crore capex project, volume dominates, so volume is what to diligence first.' },
  { id: 'c16b', topic: 'CORE-16', kind: 'mcq', q: 'What distinguishes a scenario from a sensitivity?', options: ['A scenario changes several related assumptions together into a consistent story', 'A scenario flexes one input', 'They are identical', 'A sensitivity changes all inputs'], answer: 0, why: 'A demand slowdown lowers volume, price and margin together.' },
  { id: 'c16c', topic: 'CORE-16', kind: 'mcq', q: 'The degree of financial leverage equals:', options: ['EBIT ÷ (EBIT − interest)', 'Contribution ÷ EBIT', 'Debt ÷ equity', 'EBITDA ÷ interest'], answer: 0, why: 'DOL = contribution ÷ EBIT; DFL = EBIT ÷ (EBIT − interest); their product is combined leverage.', tags: [null, 'dol_mix', 'concept', 'concept'] },

  // CORE-17 EV versus equity value
  { id: 'c17a', topic: 'CORE-17', kind: 'mcq', q: 'A company raises Rs. 100 crore of debt and holds the cash. What happens to EV and equity value at that moment?', options: ['Nothing to either', 'EV rises 100', 'Equity falls 100', 'Both rise 100'], answer: 0, why: 'Debt +100 and cash +100, so net debt is unchanged.' },
  { id: 'c17b', topic: 'CORE-17', kind: 'mcq', q: 'It then uses the cash to buy back shares. What happens?', options: ['Equity value falls 100; net debt rises 100; EV unchanged', 'EV falls 100', 'Equity value rises', 'Nothing changes'], answer: 0, why: 'Fewer shares at the same price, ignoring signalling.' },
  { id: 'c17c', topic: 'CORE-17', kind: 'mcq', q: 'Can equity value exceed enterprise value?', options: ['Yes, when cash and non-operating assets exceed debt', 'Never', 'Only for banks', 'Only after an IPO'], answer: 0, why: 'A cash-rich IT services company is the classic case.' },
  { id: 'c17d', topic: 'CORE-17', kind: 'mcq', q: 'Which pairing breaks the rule of consistency?', options: ['EV ÷ net income', 'EV ÷ EBITDA', 'Market cap ÷ PAT', 'EV ÷ revenue'], answer: 0, why: 'EV multiples use metrics available to all capital providers; equity multiples use metrics after interest.' },
  { id: 'c17e', topic: 'CORE-17', kind: 'multi', q: 'Which items might you add to EV as debt-like?', options: ['Unfunded gratuity or pension deficits', 'Deferred acquisition payments', 'Contingent liabilities likely to crystallise', 'Trade payables', 'Inventory'], answers: [0, 1, 2], why: 'Trade payables and inventory are operating working capital, not claims on the business.' },

  // CORE-18 Trading multiples
  { id: 'c18a', topic: 'CORE-18', kind: 'sort', q: 'Match the situation to the multiple the guide recommends.', buckets: ['EV/EBITDA', 'EV/EBIT', 'P/E', 'EV/Revenue', 'P/B', 'EV/tonne'], items: [['Most operating companies', 0], ['Capital-heavy business where D&A is a real cost', 1], ['Stable, profitable company; market shorthand', 2], ['Loss-making company heading to peer margins', 3], ['An NBFC', 4], ['A cement producer', 5]], why: 'Pick the multiple that reflects how the sector is valued and what drives value.' },
  { id: 'c18b', topic: 'CORE-18', kind: 'mcq', q: 'Which statistic should summarise a peer set?', options: ['Median and interquartile range', 'Mean', 'Maximum', 'The market leader'], answer: 0, why: 'Including a peer at 80x and letting the mean do the work is a trap.', tags: [null, 'mean_not_median', 'concept', 'concept'] },
  { id: 'c18c', topic: 'CORE-18', kind: 'mcq', q: 'Kaveri trades at 18.2x FY27E EBITDA against a peer median of 21.0x, with 14% growth versus a 10% peer median. What does a strong answer do?', options: ['Explains the discount (scale, liquidity, governance) before calling it undervalued', 'Declares it undervalued by 13%', 'Compares 21.2x LTM with 21.0x FY27E', 'Uses the mean instead'], answer: 0, why: 'Use the same period for all peers, and explain a gap before trading on it.', tags: [null, 'concept', 'mixed_periods', 'mean_not_median'] },
  { id: 'c18d', topic: 'CORE-18', kind: 'mcq', q: 'A company holds very large cash. How does it look on multiples?', options: ['Expensive on P/E and cheap on EV/EBITDA', 'Cheap on both', 'Expensive on both', 'Unaffected'], answer: 0, why: 'Market cap includes the cash; EV subtracts it. Heavy debt does the reverse.' },
  { id: 'c18e', topic: 'CORE-18', kind: 'mcq', q: 'For a stable company, which is right?', options: ['Forward P/E = payout ratio ÷ (cost of equity − growth)', 'P/E = growth ÷ payout', 'P/E = cost of equity − growth', 'P/E = ROE ÷ growth'], answer: 0, why: 'Multiples are compressed DCFs: higher growth and returns raise them, higher risk lowers them.' },

  // CORE-19 DCF
  { id: 'c19a', topic: 'CORE-19', kind: 'order', q: 'Order the seven steps of a DCF.', items: ['Forecast operations', 'Free cash flow to firm', 'Discount at WACC', 'Terminal value', 'Enterprise value', 'Bridge to equity value', 'Per share versus price'], why: 'FCFF = NOPAT + D&A − capex − ΔNWC; EV = PV explicit + PV terminal; then subtract net debt and other claims.' },
  { id: 'c19b', topic: 'CORE-19', kind: 'mcq', q: 'Terminal growth for an Indian company: nominal or real?', options: ['Nominal, to match nominal cash flows and WACC; typically 5 to 7%', 'Real, around 2%', 'Equal to the forecast CAGR', 'Equal to WACC'], answer: 0, why: 'Long-term growth must not exceed long-run nominal GDP growth.' },
  { id: 'c19c', topic: 'CORE-19', kind: 'mcq', q: 'If you naively grow the last explicit FCFF into the terminal value, what do you implicitly assume for Kaveri?', options: ['A 60% return on new capital, overstating value by about 9%', 'A 30% return on new capital', 'Zero growth', 'No change in value'], answer: 0, why: 'Growth needs reinvestment: rate = g ÷ RONIC. Rs. 117 versus Rs. 107 per share.', tags: [null, 'reinvestment_ignored', 'concept', 'concept'] },
  { id: 'c19d', topic: 'CORE-19', kind: 'mcq', q: 'When would you not use a DCF on FCFF?', options: ['Banks and insurers, where debt is raw material', 'Stable consumer companies', 'Utilities', 'Any listed company'], answer: 0, why: 'Use FCFE, DDM or P/B against ROE for banks; normalise cyclicals; early startups lack visibility.' },
  { id: 'c19e', topic: 'CORE-19', kind: 'mcq', q: "Kaveri's DCF gives Rs. 107 against a price of Rs. 165. What does a reverse DCF tell you?", options: ['The market is pricing faster or longer growth, or a lower discount rate', 'The DCF is wrong by definition', 'The stock must fall 35%', 'WACC is too low'], answer: 0, why: 'Even at 11.1% WACC and 7% terminal growth the DCF gives about Rs. 149. That tension is the heart of a stock pitch.' },
  { id: 'c19f', topic: 'CORE-19', kind: 'mcq', q: 'What does the mid-year convention do?', options: ['Discounts each year by half a year less, raising value slightly', 'Lowers value', 'Removes the terminal value', 'Changes WACC'], answer: 0, why: 'Cash arrives through the year, not at year end.' },

  // CORE-20 Precedents
  { id: 'c20a', topic: 'CORE-20', kind: 'mcq', q: 'Why do precedent transactions usually exceed trading multiples?', options: ['They include a control premium and reflect competitive bidding', 'They use LTM numbers', 'They ignore synergies', 'They exclude debt'], answer: 0, why: 'The buyer gets to set strategy, capture synergies and control cash flows.' },
  { id: 'c20b', topic: 'CORE-20', kind: 'mcq', q: 'Which synergies are more reliable?', options: ['Cost synergies (procurement, overheads, plants)', 'Revenue synergies (cross-selling)', 'Both equally', 'Neither'], answer: 0, why: 'Revenue synergies are uncertain and slow.' },
  { id: 'c20c', topic: 'CORE-20', kind: 'mcq', q: 'Acquiring 25% or more of a listed Indian company triggers an open offer for at least:', options: ['26% more', '25% more', '51% more', '100%'], answer: 0, why: "Under SEBI's Takeover Regulations (SAST 2011), at a price no lower than regulatory benchmarks." },
  { id: 'c20d', topic: 'CORE-20', kind: 'mcq', q: 'How should you value a cement company at a cyclical peak?', options: ['Normalised mid-cycle margins, EV per tonne or replacement cost', 'Peak-year P/E', 'Trough-year EV/EBITDA', 'Revenue multiple only'], answer: 0, why: 'Check where you are in the capacity cycle.' },

  // CORE-21 Football field, pitfalls, sector methods
  { id: 'c21a', topic: 'CORE-21', kind: 'mcq', q: "On Kaveri's football field, which method does NOT support today's Rs. 165?", options: ['DCF (Rs. 94 to 124)', 'Trading comps (Rs. 177 to 219)', 'Precedents (Rs. 171 to 211)', '52-week range (Rs. 142 to 188)'], answer: 0, why: 'Market multiples justify today\'s price; a disciplined DCF does not. The recommendation must explain the gap.' },
  { id: 'c21b', topic: 'CORE-21', kind: 'mcq', q: 'A bank earns ROE 16%, grows 10% and has a 13% cost of equity. Justified P/B?', options: ['2.0x', '1.23x', '0.67x', '1.6x'], answer: 0, why: '(16 − 10) ÷ (13 − 10) = 2.0x. At ROE 12% it deserves only 0.67x.' },
  { id: 'c21c', topic: 'CORE-21', kind: 'sort', q: 'Primary valuation method by sector.', buckets: ['P/B against ROE', 'P/EV', 'P/NAV', 'EV/ARR'], items: [['Private bank', 0], ['NBFC', 0], ['Life insurer', 1], ['Real estate developer', 2], ['B2B SaaS', 3]], why: 'Sector methods from A4.6.' },
  { id: 'c21d', topic: 'CORE-21', kind: 'mcq', q: 'Which is double counting?', options: ['Adding cash to a DCF whose EBIT already includes interest income', 'Subtracting debt in the equity bridge', 'Using diluted shares', 'Discounting at WACC'], answer: 0, why: 'Also: including leases in EV while using pre-Ind AS 116 EBITDA.' },
  { id: 'c21e', topic: 'CORE-21', kind: 'mcq', q: 'An Indian conglomerate trades below the sum of its listed parts. What should a SOTP apply?', options: ['A holding company discount, explained', 'A control premium', 'No adjustment', 'The average of all parts'], answer: 0, why: 'Cash leakage, capital allocation risk and tax on distributions explain it.' },

  // CORE-22 Debt versus equity
  { id: 'c22a', topic: 'CORE-22', kind: 'sort', q: 'Primary (money to the company) or secondary (money to sellers)?', buckets: ['Primary', 'Secondary'], items: [['Fresh issue in an IPO', 0], ['QIP', 0], ['Rights issue', 0], ['Preferential allotment', 0], ['Offer for sale in an IPO', 1], ['OFS through the exchange', 1], ['Block deal', 1]], why: '"Who gets the money?" is asked constantly.', },
  { id: 'c22b', topic: 'CORE-22', kind: 'mcq', q: 'A company raises equity at a fair price to fund projects earning above the cost of capital. Is it value-destructive because ownership falls?', options: ['No: it is value-accretive even though percentage ownership falls', 'Yes, always', 'Only for promoters', 'Only if the price is at a discount'], answer: 0, why: 'Dilution of percentage is not dilution of value.' },
  { id: 'c22c', topic: 'CORE-22', kind: 'mcq', q: 'When does debt funding raise EPS?', options: ['When returns on the money exceed the after-tax interest cost', 'Always', 'Never', 'Only if rates fall'], answer: 0, why: 'Debt: fewer shares, higher EPS if returns exceed after-tax interest; but fixed obligations and default risk.' },

  // CORE-23 Indian equity routes
  { id: 'c23a', topic: 'CORE-23', kind: 'mcq', q: 'Why might a company choose a QIP over a rights issue?', options: ['Speed and certainty: a QIP can close in days with a few institutions', 'A QIP needs all shareholders to participate', 'A QIP is priced at a deeper discount', 'A QIP needs SEBI pre-vetting'], answer: 0, why: 'Promoters who want to keep their stake prefer rights; companies wanting new institutions prefer QIPs.' },
  { id: 'c23b', topic: 'CORE-23', kind: 'mcq', q: "Under SEBI's 2025 framework, a rights issue completes in about:", options: ['23 working days', '6 to 12 months', '2 days', '90 days'], answer: 0, why: 'Rights issues became much faster from April 2025 and are now a serious alternative to QIPs.' },
  { id: 'c23c', topic: 'CORE-23', kind: 'mcq', q: 'Block deals after the revised framework (effective December 2025) need:', options: ['A minimum of Rs. 25 crore within ±3% of a reference price', 'A minimum of Rs. 10 crore within ±1%', 'No minimum', 'SEBI approval'], answer: 0, why: 'Special windows: 8:45 to 9:00 am and 2:05 to 2:20 pm. As of Sept 2026.' },
  { id: 'c23d', topic: 'CORE-23', kind: 'mcq', q: 'Which statement about buybacks is right as of September 2026?', options: ['Open-market buybacks through exchanges were reintroduced from August 2026', 'Open-market buybacks are banned', 'Buybacks can exceed 50% of capital', 'There is no leverage limit'], answer: 0, why: 'Tender offers remain; up to 25% of paid-up capital and free reserves; post-buyback D/E at most 2:1.' },
  { id: 'c23e', topic: 'CORE-23', kind: 'mcq', q: 'For frequently traded shares, the preferential allotment floor price is:', options: ['The higher of the 90-trading-day and 10-trading-day VWAP', 'The 52-week low', 'Book value', 'Any price the board chooses'], answer: 0, why: 'Allottees face a lock-in. Check the latest ICDR text before an interview.' },

  // CORE-24 Bonds
  { id: 'c24a', topic: 'CORE-24', kind: 'mcq', q: 'Two bonds have the same maturity. Which has the higher duration?', options: ['The lower-coupon bond', 'The higher-coupon bond', 'They are equal', 'The one with the higher price'], answer: 0, why: 'Higher coupons return cash sooner, so duration is lower.', tags: [null, 'concept', 'concept', 'concept'] },
  { id: 'c24b', topic: 'CORE-24', kind: 'mcq', q: 'A bond trades above par. Its yield to maturity is:', options: ['Below its coupon', 'Above its coupon', 'Equal to its coupon', 'Zero'], answer: 0, why: 'Price and yield move in opposite directions.', tags: [null, 'bond_direction', 'concept', 'concept'] },
  { id: 'c24c', topic: 'CORE-24', kind: 'mcq', q: 'Current yield is:', options: ['Coupon ÷ price', 'The same as yield to maturity', 'Coupon ÷ face value', 'The spread over G-secs'], answer: 0, why: 'Confusing current yield with YTM is a named trap.' },
  { id: 'c24d', topic: 'CORE-24', kind: 'mcq', q: 'The 10-year 7% bond is 95.24 at 7.7% and 102.14 at 6.7% (98.61 at 7.2%). What property does the asymmetry show?', options: ['Convexity: price rises more when yields fall than it drops when they rise', 'Negative duration', 'Credit spread', 'Reinvestment risk only'], answer: 0, why: 'Duration is the tangent; the true curve bends above it.' },
  { id: 'c24e', topic: 'CORE-24', kind: 'mcq', q: '"Net debt/EBITDA below 3x, tested quarterly" is:', options: ['A maintenance covenant', 'An incurrence covenant', 'A negative pledge', 'A rating trigger'], answer: 0, why: 'Incurrence covenants limit new debt, dividends or asset sales when you act.' },

  // CORE-25 Payout, refinancing, liquidity
  { id: 'c25a', topic: 'CORE-25', kind: 'mcq', q: 'Why does a dividend increase signal confidence?', options: ['Dividends are sticky: companies are reluctant to cut them', 'Dividends are tax-free', 'They reduce debt', 'They raise EPS'], answer: 0, why: 'Buybacks are flexible and can signal undervaluation.' },
  { id: 'c25b', topic: 'CORE-25', kind: 'mcq', q: 'After Budget 2026, how are buyback proceeds taxed for shareholders?', options: ['As capital gains again, with an extra levy on promoters', 'As deemed dividend at slab rates', 'Not taxed', 'As business income'], answer: 0, why: 'This narrows the tax arbitrage promoters used to enjoy. As of Sept 2026; verify before interviews.' },
  { id: 'c25c', topic: 'CORE-25', kind: 'mcq', q: 'Which company carries the most refinancing risk?', options: ['Moderate leverage but most debt maturing next year', 'High leverage spread over 10 years', 'No debt', 'Undrawn committed facilities'], answer: 0, why: 'A maturity wall makes a company fragile even if leverage looks moderate.' },

  // CORE-26 Macro
  { id: 'c26a', topic: 'CORE-26', kind: 'mcq', q: "If the risk-free rate rises 0.5% and the ERP is unchanged, what happens to Kaveri's DCF value?", options: ['About Rs. 107 → Rs. 98, roughly 8% lower', 'No change', 'About Rs. 107 → Rs. 117', 'It halves'], answer: 0, why: "WACC rises from about 12.1% to 12.6%. That is why growth stocks sell off when bond yields jump." },
  { id: 'c26b', topic: 'CORE-26', kind: 'sort', q: 'The rupee weakens. Who benefits and who is hurt?', buckets: ['Benefits', 'Hurt'], items: [['IT services exporters', 0], ['Pharma exporters', 0], ['Oil marketing companies', 1], ['Airlines', 1], ['Electronics importers', 1], ['Companies with unhedged foreign currency debt', 1]], why: 'Exporters earn more rupees; importers and unhedged borrowers pay more.' },
  { id: 'c26c', topic: 'CORE-26', kind: 'mcq', q: 'You expect rate cuts. In an overnight indexed swap you should:', options: ['Receive fixed', 'Pay fixed', 'Do nothing', 'Buy a floating-rate note'], answer: 0, why: 'You lock today\'s fixed rate and pay the floating rate, which falls if cuts happen.' },
  { id: 'c26d', topic: 'CORE-26', kind: 'mcq', q: 'As of the 5 Aug 2026 policy, the repo rate and stance were:', options: ['5.25%, neutral', '6.50%, withdrawal of accommodation', '5.50%, accommodative', '4.00%, neutral'], answer: 0, why: 'SDF 5.00%, MSF 5.50%; next MPC decision 7 Oct 2026. Update before every interview.' },
  { id: 'c26e', topic: 'CORE-26', kind: 'mcq', q: 'Crude oil rises sharply. Who is hurt?', options: ['Paints, tyres, airlines, oil marketers', 'Upstream oil producers', 'IT services', 'Gold miners'], answer: 0, why: 'India imports most of its oil: pressure on inflation, the current account and the rupee.' },

  // CORE-27 Excel
  { id: 'c27a', topic: 'CORE-27', kind: 'sort', q: 'Apply the model colour code.', buckets: ['Blue font', 'Black font', 'Green font'], items: [['Hard-coded inputs', 0], ['Formulas', 1], ['Links to other sheets', 2]], why: 'Never hard-code a number inside a formula.' },
  { id: 'c27b', topic: 'CORE-27', kind: 'mcq', q: 'Interest on average debt creates a circular reference with cash. What do you do?', options: ['Use a circuit-breaker switch or interest on opening balances', 'Turn on iterative calculation and forget it', 'Hard-code interest', 'Delete the cash sweep'], answer: 0, why: 'A model that does not balance fails the test regardless of anything else.' },
  { id: 'c27c', topic: 'CORE-27', kind: 'mcq', q: 'Which functions should you avoid in shared models?', options: ['OFFSET, INDIRECT and merged cells', 'SUMIFS and XLOOKUP', 'NPV and IRR', 'MIN and MAX'], answer: 0, why: 'They break easily and are hard to audit.' },
  { id: 'c27d', topic: 'CORE-27', kind: 'order', q: 'Order the approach to a timed modelling test.', items: ['Build the skeleton: years, headers, check rows', 'Get the model balancing with rough assumptions', 'Refine the assumptions', 'Reach and state the answer'], why: 'A simple model that balances beats a sophisticated one that does not.' },
  { id: 'c27e', topic: 'CORE-27', kind: 'mcq', q: 'In Excel on Windows, what does F4 do while editing a reference?', options: ['Cycles $A$1, A$1, $A1', 'Recalculates', 'Opens Format Cells', 'Fills down'], answer: 0, why: 'Ctrl + D fills down; Ctrl + 1 formats cells; F9 recalculates.' },

  // CORE-28 Communicating a recommendation
  { id: 'c28a', topic: 'CORE-28', kind: 'order', q: 'Order a recommendation using the pyramid principle.', items: ['The recommendation', 'Three reasons', 'Evidence for each reason', 'Risks: what would make us wrong'], why: 'Answer first, then the reasons, then the evidence.' },
  { id: 'c28b', topic: 'CORE-28', kind: 'mcq', q: 'Which answer rounds intelligently?', options: ['"About 36 days"', '"35.836 days"', '"Somewhere between 30 and 40"', '"I would need Excel"'], answer: 0, why: 'Round intelligently and show your working.' },
  { id: 'c28c', topic: 'CORE-28', kind: 'mcq', q: 'You do not know the answer. The strong move is:', options: ['Say so, then reason from first principles', 'Answer confidently anyway', 'Change the subject', 'Ask to skip'], answer: 0, why: 'Interviewers reported rejecting candidates for confident wrong answers.' },

  // CORE-29 Industry research
  { id: 'c29a', topic: 'CORE-29', kind: 'mcq', q: 'What is the most efficient single source on an Indian sector?', options: ['The DRHP of the most recent IPO in the sector', 'A news article', 'Wikipedia', 'The company\'s Twitter feed'], answer: 0, why: 'It contains an independent industry report, business description, risk factors and peer comparisons. Read "Industry overview" and "Our business" first.' },
  { id: 'c29b', topic: 'CORE-29', kind: 'sort', q: 'Where do you find each section of a company primer?', buckets: ['Annual report, investor presentation, DRHP', 'Rating agency reports, broker initiations', 'Concalls, channel checks', 'Screener, annual reports'], items: [['Business model', 0], ['Industry structure', 1], ['Competitive position', 2], ['Five-year financials', 3]], why: 'Template from A6.4.' },
  { id: 'c29c', topic: 'CORE-29', kind: 'mcq', q: 'How many sectors should you be able to discuss for 15 minutes?', options: ['Two', 'One', 'Five', 'Every sector'], answer: 0, why: 'Structure, economics, players, valuation and recent deals.' },
];
