import type { StaticDrill } from './types';

// Static drills for Part B (Investment banking), grounded in chapters B1 to B6.
export const IB_DRILLS: StaticDrill[] = [
  // IB-01 Products
  { id: 'b01a', topic: 'IB-01', kind: 'sort', q: 'Which product group does each activity belong to?', buckets: ['M&A advisory', 'ECM', 'DCM', 'Leveraged and acquisition finance', 'Restructuring'], items: [['Advise a seller: valuation, counterparties, negotiation', 0], ['IPOs, FPOs, QIPs, rights issues, OFS, block deals', 1], ['Bonds, NCDs, commercial paper, loan syndication', 2], ['Structure debt for acquisitions and buyouts', 3], ['Resolution plans under the IBC', 4]], why: 'An investment bank sells advice on transactions and access to capital.' },
  { id: 'b01b', topic: 'IB-01', kind: 'mcq', q: 'Which product dominates Indian investment banking fee pools?', options: ['Equity capital markets', 'Restructuring', 'Leveraged finance', 'Debt capital markets'], answer: 0, why: 'India has one of the world\'s most active primary markets, so expect IPO process questions even for an M&A seat.' },
  { id: 'b01c', topic: 'IB-01', kind: 'mcq', q: 'Who manages public issues in India?', options: ['SEBI-registered merchant bankers acting as book running lead managers', 'The stock exchanges', 'Registrars', 'Statutory auditors'], answer: 0, why: 'BRLMs run the IPO; the registrar processes applications and allotment.' },

  // IB-18 How the bank earns
  { id: 'b18a', topic: 'IB-18', kind: 'mcq', q: 'How is an M&A adviser typically paid?', options: ['A retainer (sometimes) and a success fee at closing, as a percentage of deal value', 'A fixed hourly rate', 'Only a retainer', 'A share of the buyer\'s future profits'], answer: 0, why: 'Most revenue arrives only when a deal closes, so banks pitch many ideas to win a few mandates.' },
  { id: 'b18b', topic: 'IB-18', kind: 'mcq', q: 'A bank advises a seller while its lending arm finances a buyer. What manages this?', options: ['Chinese walls and compliance processes', 'Nothing: it is prohibited', 'The client\'s auditor', 'SEBI pre-approval of each deal'], answer: 0, why: 'Conflicts also arise when research covers a company its bankers are pitching.' },
  { id: 'b18c', topic: 'IB-18', kind: 'mcq', q: 'Why do domestic banks compete on volume and distribution in Indian ECM?', options: ['Indian ECM fee rates are much lower than in the US', 'SEBI caps the number of IPOs', 'Global banks cannot do IPOs', 'Retail investors pay the fees'], answer: 0, why: 'Main-board IPOs raised about Rs. 1.76 lakh crore across 103 issues in 2025.' },

  // IB-19 Coverage versus product
  { id: 'b19a', topic: 'IB-19', kind: 'sort', q: 'Place each transaction in the product column of the coverage-by-product grid.', buckets: ['M&A advisory', 'ECM', 'DCM', 'Leveraged and acquisition finance'], items: [['NBFC stake sale', 0], ['Renewables stake sale', 0], ['Consumer brand IPO', 1], ['InvIT or REIT listing', 1], ['AT1 and tier 2 bonds', 2], ['Green bonds', 2], ['Sponsor acquisition loan', 3], ['Take-private debt', 3]], why: 'A live deal is staffed from both axes: the coverage banker owns the client; the product team brings execution skill.' },
  { id: 'b19b', topic: 'IB-19', kind: 'mcq', q: 'Who owns the client relationship on a live deal?', options: ['The coverage (industry) banker', 'The product team', 'The analyst', 'Compliance'], answer: 0, why: 'In smaller Indian firms the axes blur: a team of eight may cover a sector and execute M&A and ECM together.' },

  // IB-20 Deal team
  { id: 'b20a', topic: 'IB-20', kind: 'order', q: 'Order the deal team from most to least senior.', items: ['Managing Director', 'Director / Executive Director', 'Vice President', 'Associate / AVP', 'Analyst'], why: 'Titles vary by firm; responsibilities are consistent.' },
  { id: 'b20b', topic: 'IB-20', kind: 'sort', q: 'Who does what?', buckets: ['MD', 'Director', 'VP', 'Associate', 'Analyst'], items: [['Owns client relationships, originates mandates, signs off', 0], ['Runs several deals, senior negotiation, pitches', 1], ['Day-to-day deal manager, reviews all output', 2], ['Checks models, drafts documents, coordinates advisers', 3], ['Models, comps, CIMs, pitch pages, data room', 4]], why: 'An MBA hire typically joins as an Associate (or AVP at some Indian firms).' },
  { id: 'b20c', topic: 'IB-20', kind: 'mcq', q: 'What does the associate job reward most?', options: ['Accuracy, ownership and anticipating what the VP and MD will ask next', 'Originating mandates', 'Setting fees', 'Signing engagement letters'], answer: 0, why: 'First-year work: build and check models, draft pitchbooks, CIMs and offer documents, run data rooms, coordinate advisers, manage analysts.' },

  // IB-21 Origination
  { id: 'b21a', topic: 'IB-21', kind: 'order', q: 'Order the origination pipeline.', items: ['Sector idea', 'Pitch (often unsolicited)', 'Mandate (engagement letter signed)', 'Staffing', 'Execution', 'Closing', 'Repeat business'], why: 'Most pitches never become mandates.' },
  { id: 'b21b', topic: 'IB-21', kind: 'mcq', q: 'What turns a pitch into a mandate?', options: ['A signed engagement letter', 'A verbal yes', 'A first draft CIM', 'Board minutes of the bank'], answer: 0, why: 'After that the bank staffs the deal and begins execution.' },

  // IB-22 Interfaces
  { id: 'b22a', topic: 'IB-22', kind: 'sort', q: 'Match each party to its role in a deal.', buckets: ['Lawyers', 'Statutory auditors', 'Big 4 / diligence firms', 'SEBI and exchanges', 'Registrar to the issue', 'CCI, RBI and sector regulators'], items: [['SPA and SHA drafting, offer documents', 0], ['Restated financials, comfort letters for IPOs', 1], ['Financial and tax due diligence, vendor due diligence', 2], ['Review offer documents, in-principle approvals, listing', 3], ['Processes applications and allotment in IPOs', 4], ['Merger control, foreign investment and sector approvals', 5]], why: 'The bank coordinates this web of parties.' },

  // IB-16 Indian landscape
  { id: 'b16a', topic: 'IB-16', kind: 'sort', q: 'Classify each firm.', buckets: ['Global bank in India', 'Domestic full-service bank', 'Advisory boutique', 'Big 4 deal advisory'], items: [['JP Morgan', 0], ['Jefferies', 0], ['Kotak Mahindra Capital', 1], ['JM Financial', 1], ['Axis Capital', 1], ['Avendus', 2], ['Spark Capital', 2], ['EY', 3], ['Grant Thornton Bharat', 3]], why: 'Global banks lead on the largest and cross-border deals; domestic banks on IPO volume; boutiques on mid-market M&A; Big 4 on diligence and valuation.' },
  { id: 'b16b', topic: 'IB-16', kind: 'mcq', q: 'Which bank led the most main-board IPO mandates in calendar 2025?', options: ['JM Financial (17)', 'Kotak Mahindra Capital (8)', 'Citi (5)', 'HSBC (6)'], answer: 0, why: 'Followed by IIFL Capital (12) and Motilal Oswal (11). Source: 5paisa compilation of Prime Database data.' },
  { id: 'b16c', topic: 'IB-16', kind: 'mcq', q: 'What is the strength of domestic full-service banks?', options: ['Domestic institutional and retail distribution; volume leaders in IPOs', 'Cross-border M&A', 'Hedge fund prime brokerage', 'Only restructuring'], answer: 0, why: 'For you: broad deal exposure early and ECM-heavy work.' },
  { id: 'b16d', topic: 'IB-16', kind: 'order', q: 'Order the steps for researching a bank before an interview.', items: ['List its last 10 to 15 deals', 'Map its sector strengths and the people who lead them', 'Study one recent deal in depth', 'Explain how it differs from its closest competitor'], why: '"Why Avendus and not Kotak?" needs a real answer.' },

  // IB-02 Sell-side
  { id: 'b02a', topic: 'IB-02', kind: 'order', q: 'Order the stages of a controlled sell-side auction.', items: ['Preparation: mandate, VDD, model, teaser, CIM, buyer list', 'Marketing: teasers out, NDAs, CIM, non-binding offers', 'Due diligence: data room, management meetings, binding bids', 'Negotiate and sign: SPA / SHA mark-ups, signing', 'Close: CCI and other approvals, conditions precedent, funds flow'], why: 'An indicative Indian mid-market auction runs about 24 weeks; large or regulated deals run longer.' },
  { id: 'b02b', topic: 'IB-02', kind: 'mcq', q: "What is the teaser's job?", options: ['Get NDAs signed', 'Support a binding bid', 'Replace the CIM', 'Disclose the price'], answer: 0, why: 'It is short (1 to 2 pages) and anonymous. The CIM (40 to 80 pages) supports a non-binding offer.' },
  { id: 'b02c', topic: 'IB-02', kind: 'mcq', q: 'What is the difference between signing and closing?', options: ['Signing executes the agreement; closing is when ownership and money change hands after conditions precedent are met', 'They are the same day', 'Closing comes first', 'Signing needs CCI approval'], answer: 0, why: 'In India the gap can be months if CCI or RBI approval or an NCLT scheme is required.' },
  { id: 'b02d', topic: 'IB-02', kind: 'mcq', q: 'Why run a controlled auction rather than a negotiated sale?', options: ['Competition creates price tension', 'It is faster', 'It is more confidential', 'It avoids due diligence'], answer: 0, why: 'A negotiated sale is faster and more confidential but gives up price tension.' },

  // IB-03 Buy-side and Indian structures
  { id: 'b03a', topic: 'IB-03', kind: 'order', q: 'Order a typical buy-side sequence.', items: ['Strategic rationale', 'Target screening', 'Approach', 'Indicative offer', 'Diligence', 'Financing commitments', 'Binding offer and SPA', 'Approvals and closing'], why: 'Integration follows closing.' },
  { id: 'b03b', topic: 'IB-03', kind: 'mcq', q: 'What is your main value as the buy-side adviser?', options: ['Discipline: an independent valuation, a clear walk-away price and early deal-breakers', 'Maximising the price paid', 'Writing the CIM', 'Running the auction'], answer: 0, why: 'Overpaying and overestimating synergies are why most acquisitions fail to create value.' },
  { id: 'b03c', topic: 'IB-03', kind: 'mcq', q: 'Since September 2024, CCI approval is also needed for deals with a transaction value above:', options: ['Rs. 2,000 crore, where the target has substantial business operations in India', 'Rs. 500 crore', 'Rs. 10,000 crore', 'US$1 billion'], answer: 0, why: 'In addition to the asset and turnover thresholds.' },
  { id: 'b03d', topic: 'IB-03', kind: 'mcq', q: 'A merger through a scheme of arrangement needs approval from:', options: ['Shareholders, creditors, stock exchanges (if listed) and the NCLT', 'Only the board', 'Only SEBI', 'Only the RBI'], answer: 0, why: 'Sections 230 to 232 of the Companies Act; it can take 6 to 12 months.' },
  { id: 'b03e', topic: 'IB-03', kind: 'mcq', q: "RBI's 2026 acquisition finance directions let banks fund control deals from 1 April 2026 up to:", options: ['75% of deal value, with acquirer net worth of at least Rs. 500 crore and post-deal D/E of at most 3:1', '100% of deal value', '50% of deal value with no other conditions', 'Nothing: banks still cannot fund share purchases'], answer: 0, why: 'A big change from the earlier restriction. As of Sept 2026; verify before interviews.' },
  { id: 'b03f', topic: 'IB-03', kind: 'mcq', q: 'What does Press Note 3 require?', options: ['Government approval for investors from countries sharing a land border with India', 'CCI approval for all deals', 'An open offer at 5%', 'SEBI approval for unlisted deals'], answer: 0, why: 'Cross-border deals also face FEMA pricing guidelines and sectoral FDI caps.' },

  // IB-04 Accretion and PPA
  { id: 'b04a', topic: 'IB-04', kind: 'mcq', q: 'In an all-stock deal with no synergies, when is it accretive?', options: ["When the acquirer's P/E exceeds the P/E paid", "When the target's P/E exceeds the acquirer's", 'Always', 'Never'], answer: 0, why: 'A low-P/E company buying a high-P/E company with stock is dilutive.', tags: [null, 'accretion_sign', 'concept', 'concept'] },
  { id: 'b04b', topic: 'IB-04', kind: 'mcq', q: 'In an all-debt deal, you compare the target\'s earnings yield at the purchase price with:', options: ['The after-tax cost of debt (or forgone interest on cash)', 'The acquirer\'s P/E', 'The pre-tax cost of debt', 'WACC'], answer: 0, why: 'Kaveri paying 15x: target yield 6.7% versus a blended cost of 5.88% (half stock at 5.0%, half debt at 6.75% after tax), so accretive.', tags: [null, 'concept', 'forgot_tax', 'concept'] },
  { id: 'b04c', topic: 'IB-04', kind: 'mcq', q: 'Kaveri (20x P/E in this example) pays 25x, all in stock. EPS falls 2.9%. About how much pre-tax synergy breaks even?', options: ['Rs. 10 crore a year', 'Rs. 7.5 crore a year', 'Rs. 30 crore a year', 'Rs. 2.5 crore a year'], answer: 0, why: 'Needed NI = 4.50 × 58.33 = 262.5, so 7.5 after tax, which is 10 pre-tax at 25%.', tags: [null, 'forgot_tax', 'concept', 'concept'] },
  { id: 'b04d', topic: 'IB-04', kind: 'mcq', q: 'Is an accretive deal a good deal?', options: ['Not necessarily: it can be accretive and still destroy value if the price exceeds what the target is worth to the buyer', 'Yes, always', 'Only if it is all-cash', 'Only if it is all-stock'], answer: 0, why: 'Boards watch EPS, but EPS accretion is not value creation.' },
  { id: 'b04e', topic: 'IB-04', kind: 'mcq', q: 'After a PPA, which item reduces future EPS and belongs in accretion analysis?', options: ['Amortisation of finite-life intangibles', 'Goodwill amortisation', 'The deferred tax liability', 'Transaction fees already paid'], answer: 0, why: 'Goodwill is not amortised under Ind AS; it is tested for impairment.' },

  // IB-05 Deal terms
  { id: 'b05a', topic: 'IB-05', kind: 'mcq', q: 'The price is fixed on a past balance sheet with leakage protection. This is:', options: ['A locked box', 'Completion accounts', 'An earn-out', 'An escrow'], answer: 0, why: 'A locked box gives price certainty to the seller; completion accounts protect the buyer.' },
  { id: 'b05b', topic: 'IB-05', kind: 'mcq', q: 'What does a working capital peg stop?', options: ['Sellers stripping working capital before closing', 'Buyers walking away', 'Tax disputes', 'Price discovery'], answer: 0, why: 'The price adjusts rupee for rupee if actual NWC is above or below the target level.' },
  { id: 'b05c', topic: 'IB-05', kind: 'mcq', q: 'In a cash-free, debt-free deal:', options: ['The buyer pays EV; the seller keeps cash and repays debt at closing', 'The buyer takes on all debt', 'The seller keeps the debt', 'No working capital is delivered'], answer: 0, why: 'It is paired with a normal level of working capital.' },
  { id: 'b05d', topic: 'IB-05', kind: 'mcq', q: 'What is the main risk of an earn-out?', options: ['Disputes if metrics are vague', 'It always overpays', 'It is illegal in India', 'It ignores valuation gaps'], answer: 0, why: 'Earn-outs bridge valuation gaps.' },
  { id: 'b05e', topic: 'IB-05', kind: 'mcq', q: 'What can change the price after the first round?', options: ['Diligence findings, financing conditions, market moves, competitive tension and trading', 'Nothing: first-round prices are binding', 'Only the seller\'s mood', 'Only regulators'], answer: 0, why: 'Lower normalised EBITDA, debt-like items and working capital are the usual culprits.' },

  // IB-06 Diligence
  { id: 'b06a', topic: 'IB-06', kind: 'sort', q: 'Which workstream answers each question?', buckets: ['Financial', 'Tax', 'Legal', 'Commercial', 'Operational and technology', 'HR and ESG'], items: [['Normalised EBITDA and the working capital peg', 0], ['Pending disputes and structuring exposure', 1], ['Title, licences, change-of-control clauses', 2], ['Market size, competitive position, customer interviews', 3], ['Plant condition, IT systems, cybersecurity', 4], ['Key people, labour issues, environmental liabilities', 5]], why: 'Big 4 firms run financial diligence; consultants or the buyer\'s own team run commercial.' },
  { id: 'b06b', topic: 'IB-06', kind: 'mcq', q: 'Which of these is a debt-like item that reduces the equity price?', options: ['Unpaid statutory dues', 'Inventory', 'Trade receivables', 'PP&E'], answer: 0, why: 'Also gratuity shortfalls, overdue creditors, tax exposures and earn-outs from past acquisitions.' },

  // IB-15 Data room and closing mechanics
  { id: 'b15a', topic: 'IB-15', kind: 'order', q: 'Order the life of a question in the data room Q&A tracker.', items: ['Logged', 'Assigned', 'Answered', 'Reviewed', 'Released'], why: 'As an associate you will live inside the Q&A tracker.' },
  { id: 'b15b', topic: 'IB-15', kind: 'mcq', q: 'Who builds and controls the virtual data room in a sale?', options: ['The sell-side bank, organised by workstream with access controlled by bidder', 'Each bidder', 'The regulator', 'The buyer\'s lawyers'], answer: 0, why: 'The bank also rehearses management for a 2 to 3 hour presentation.' },

  // IB-07 IPO process
  { id: 'b07a', topic: 'IB-07', kind: 'order', q: 'Order the main-board IPO journey.', items: ['Readiness: board, restated financials, appoint BRLMs', 'DRHP filed with SEBI and exchanges', 'SEBI review and observations', 'RHP filed; marketing and price band', 'Book building: anchor day, then bidding', 'Allotment and listing'], why: 'SEBI observations are valid for 12 months.' },
  { id: 'b07b', topic: 'IB-07', kind: 'mcq', q: 'After the issue closes on day T, when do allotment, credit and listing happen?', options: ['Allotment T+1, credit and refunds T+2, listing T+3', 'Listing T+6', 'Listing T+1', 'Allotment T+3, listing T+10'], answer: 0, why: 'Bidding runs for at least three working days through ASBA and UPI.' },
  { id: 'b07c', topic: 'IB-07', kind: 'mcq', q: 'How are anchor investors locked in?', options: ['50% for 30 days and 50% for 90 days', '100% for one year', 'No lock-in', '18 months'], answer: 0, why: 'Anchors are allotted one working day before the issue opens, which signals quality to the book.' },
  { id: 'b07d', topic: 'IB-07', kind: 'mcq', q: 'From 30 November 2025, how much of the anchor portion is reserved for domestic institutions?', options: ['40%: 33% for mutual funds and 7% for insurers and pension funds', 'One-third for mutual funds only', '60%', 'None'], answer: 0, why: 'Up from one-third earlier. As of Sept 2026; verify before interviews.' },
  { id: 'b07e', topic: 'IB-07', kind: 'mcq', q: 'The price band cap can be at most:', options: ['120% of the floor', '105% of the floor', '150% of the floor', 'Any level'], answer: 0, why: 'The band is announced at least two working days before opening.' },
  { id: 'b07f', topic: 'IB-07', kind: 'mcq', q: 'A loss-making new-age company lists under Regulation 6(2). What must it allocate to QIBs?', options: ['At least 75% of the issue', 'Up to 50%', 'At least 35%', 'Nothing'], answer: 0, why: 'It fails the Regulation 6(1) track-record tests (net tangible assets, average operating profit of at least Rs. 15 crore over three years, net worth).' },
  { id: 'b07g', topic: 'IB-07', kind: 'mcq', q: 'Beyond headline subscription, what do bankers look at in the book?', options: ['Quality and price sensitivity of QIB demand, demand at the cut-off, anchor composition', 'Only the grey market premium', 'Only retail subscription', 'The number of applications'], answer: 0, why: 'A deal priced so aggressively that it falls on listing damages the bank\'s and issuer\'s reputation.' },

  // IB-17 SEBI framework
  { id: 'b17a', topic: 'IB-17', kind: 'mcq', q: 'What is the minimum promoter contribution and its lock-in?', options: ['20% of post-issue capital, locked for 18 months (three years if proceeds fund capex)', '51% for five years', '10% for six months', 'No minimum'], answer: 0, why: 'Promoter holding above that and pre-IPO shareholders\' holdings are locked for six months.' },
  { id: 'b17b', topic: 'IB-17', kind: 'mcq', q: 'General corporate purposes are capped at:', options: ['25% of the fresh issue (35% combined with unidentified acquisitions)', '50% of the issue', '10% of the issue', 'No cap'], answer: 0, why: 'A monitoring agency tracks use of fresh-issue proceeds.' },
  { id: 'b17c', topic: 'IB-17', kind: 'mcq', q: 'How does the RHP differ from the final prospectus?', options: ['The RHP has everything except the final price', 'The RHP is never public', 'The RHP is filed after listing', 'They are identical'], answer: 0, why: 'The DRHP goes to SEBI for observations; the RHP is filed with the RoC before marketing; the prospectus after pricing.' },
  { id: 'b17d', topic: 'IB-17', kind: 'mcq', q: 'Since 2022, what option lets issuers keep the draft private until closer to launch?', options: ['Confidential pre-filing', 'A private placement memorandum', 'A shelf prospectus', 'A QIP'], answer: 0, why: 'Check the current SEBI master circular (February 2026) for practical scope.' },

  // IB-08 Fresh issue versus OFS
  { id: 'b08a', topic: 'IB-08', kind: 'mcq', q: 'In an offer for sale, who gets the money?', options: ['The selling shareholders; no new shares are created', 'The company', 'Both equally', 'The BRLMs'], answer: 0, why: 'A fresh issue creates new shares and dilutes everyone; an OFS only moves existing shares.', tags: [null, 'fresh_vs_ofs', 'fresh_vs_ofs', 'concept'] },
  { id: 'b08b', topic: 'IB-08', kind: 'sort', q: 'Classify each recent IPO.', buckets: ['Entirely OFS', 'Fresh issue plus OFS'], items: [['Hyundai Motor India (Oct 2024, ~Rs. 27,870 crore)', 0], ['LG Electronics India (Oct 2025, ~Rs. 11,600 crore)', 0], ['NSE (Sep 2026, ~Rs. 22,563 crore)', 0], ['Tata Capital (Oct 2025, ~Rs. 15,500 crore)', 1]], why: 'Hyundai remains India\'s largest IPO as of Sept 2026.' },
  { id: 'b08c', topic: 'IB-08', kind: 'mcq', q: 'A growth company\'s IPO is mostly OFS. What does it signal?', options: ['Existing holders want to sell: fine for a mature business, but questions if it needs growth capital', 'The company is raising a lot of money', 'The promoter is buying', 'Nothing'], answer: 0, why: 'Only the fresh issue brings money into the company.' },
  { id: 'b08d', topic: 'IB-08', kind: 'mcq', q: 'Why do promoters of profitable companies run mostly-OFS IPOs?', options: ['Liquidity and exit for early investors, price discovery, brand and governance, minimum public shareholding', 'To raise growth capital', 'To avoid SEBI review', 'To increase their stake'], answer: 0, why: 'A genuine interview question.' },

  // IB-09 Follow-ons
  { id: 'b09a', topic: 'IB-09', kind: 'sort', q: 'Match the follow-on route to its feature.', buckets: ['QIP', 'Rights issue', 'Preferential allotment', 'FPO', 'OFS through the exchange'], items: [['Institutions only; days to weeks', 0], ['Existing holders pro rata; about 23 working days', 1], ['Named investors; shareholder approval; pricing floor', 2], ['Full public offering with an offer document', 3], ['Sellers use it; minimum Rs. 25 crore; 10% retail reservation', 4]], why: 'Chapter A5 compares the routes in detail.' },
  { id: 'b09b', topic: 'IB-09', kind: 'mcq', q: "Vodafone Idea's April 2024 FPO of Rs. 18,000 crore was notable because:", options: ["It is India's largest follow-on public offer", 'It was withdrawn', 'It was all OFS', 'It was a QIP'], answer: 0, why: "Adani Enterprises' 2023 FPO (Rs. 20,000 crore) was fully subscribed and then withdrawn after a short-seller report." },
  { id: 'b09c', topic: 'IB-09', kind: 'mcq', q: 'A promoter wants Rs. 500 crore quickly and wants to keep their stake. Which route?', options: ['A rights issue, if shareholders support it', 'A QIP', 'An OFS', 'A block deal'], answer: 0, why: 'QIP if institutional demand exists and speed matters; preferential if a strategic investor is ready.' },

  // IB-10 Buyback and open offer
  { id: 'b10a', topic: 'IB-10', kind: 'mcq', q: 'What triggers a mandatory open offer in India?', options: ['Acquiring 25% or more of voting rights or control, or creeping above 5% a year between 25% and the maximum non-public holding', 'Any purchase above 10%', 'Only acquiring 51%', 'Any preferential allotment'], answer: 0, why: 'The offer must be for at least 26% more, at a price no lower than regulatory benchmarks.' },
  { id: 'b10b', topic: 'IB-10', kind: 'mcq', q: 'What are the key questions on a buyback?', options: ['Purpose, price relative to market, acceptance ratios and tax', 'Only the dividend history', 'The auditor\'s name', 'The number of BRLMs'], answer: 0, why: 'Tax changed with Budget 2026 and open-market buybacks returned from August 2026.' },

  // IB-11 DCM and acquisition finance
  { id: 'b11a', topic: 'IB-11', kind: 'sort', q: 'Bank loan or bond / NCD?', buckets: ['Bank loan', 'Bond or NCD'], items: [['Floating rate linked to MCLR or an external benchmark', 0], ['Easy to amend; prepayable', 0], ['Maintenance covenants tested regularly', 0], ['Many investors: mutual funds, insurers, pension funds', 1], ['Usually lighter, incurrence-based covenants', 1], ['Rated; listed ones carry continuous disclosure', 1]], why: 'Lenders focus on the downside: coverage, security, covenants.' },
  { id: 'b11b', topic: 'IB-11', kind: 'order', q: 'Order a rated NCD issue.', items: ['Mandate', 'Credit rating process', 'Term sheet', 'Investor sounding', 'Pricing on the exchange EBP platform', 'Allotment and listing', 'Ongoing servicing'], why: 'The DCM craft is reading investor appetite: the right tenor and structure save basis points.' },
  { id: 'b11c', topic: 'IB-11', kind: 'mcq', q: 'Should an acquisition be funded with equity rather than debt?', options: ["Equity if the target is risky, leverage is already high, or the acquirer's shares are richly valued", 'Always debt', 'Always equity', 'Equity only if rates are low'], answer: 0, why: 'Debt fits stable cash flows, leverage within target and undervalued acquirer shares.' },

  // IB-12 Pitchbook
  { id: 'b12a', topic: 'IB-12', kind: 'order', q: 'Order a typical pitchbook.', items: ['Situation overview', 'Sector perspectives', 'Strategic options', 'Valuation perspectives', 'Recommended option and process', 'Bank credentials'], why: 'A pitchbook argues for a transaction and for the bank, usually in 20 to 40 pages.' },
  { id: 'b12b', topic: 'IB-12', kind: 'mcq', q: 'In a five-slide mock pitch, each slide should carry:', options: ['One message, stated in the title', 'As many charts as fit', 'A full DCF', 'The bank logo only'], answer: 0, why: 'Present it to a friend in five minutes.' },

  // IB-13 Models
  { id: 'b13a', topic: 'IB-13', kind: 'sort', q: 'Which check does a VP ask for on each model?', buckets: ['Three-statement', 'DCF', 'Trading comps', 'Merger model', 'LBO'], items: [['Balance sheet balances; cash ties', 0], ['Terminal value share; implied exit multiple', 1], ['Calendarisation to March year-ends; diluted shares', 2], ['Funding mix, PPA, synergy phasing', 3], ['IRR at different prices', 4]], why: 'Precedents: relevance and age of deals, LTM at announcement, premium.' },
  { id: 'b13b', topic: 'IB-13', kind: 'mcq', q: 'What is a common modelling test format?', options: ['A 60 to 180 minute three-statement model or simple LBO from a case pack', 'A 10-minute Excel quiz', 'A week-long project', 'An oral exam only'], answer: 0, why: 'Or a take-home DCF on a listed company. Practise with a timer.' },

  // IB-14 Discussing a deal
  { id: 'b14a', topic: 'IB-14', kind: 'order', q: 'Order the six-part deal discussion.', items: ['Facts', 'Rationale', 'Valuation', 'Financing and structure', 'Market reaction', 'Your view'], why: '"Tell me about a recent deal" is asked in almost every IB interview. Practise until it takes three minutes.' },
  { id: 'b14b', topic: 'IB-14', kind: 'mcq', q: "Sun Pharmaceutical's acquisition of Organon was announced in:", options: ['April 2026, about US$11.75 billion, all cash', 'July 2025, €3.8 billion', 'October 2025, about Rs. 26,850 crore', 'December 2025, US$2.35 billion'], answer: 0, why: 'The largest outbound deal by an Indian company in years. The others are Tata Motors–Iveco, Emirates NBD–RBL and Coforge–Encora.' },
  { id: 'b14c', topic: 'IB-14', kind: 'mcq', q: "What made Emirates NBD's deal for RBL Bank notable?", options: ['About 60% of an Indian private bank via primary infusion plus open offer', 'It was an all-OFS IPO', 'It was a share swap in IT services', 'It was a European tender offer'], answer: 0, why: 'Announced October 2025, about Rs. 26,850 crore.' },
  { id: 'b14d', topic: 'IB-14', kind: 'mcq', q: 'The NSE IPO (September 2026) was:', options: ['An all-OFS listing of a market infrastructure institution, listed on BSE', 'A fresh issue to fund expansion', 'A QIP', 'A rights issue'], answer: 0, why: 'About Rs. 22,563 crore at Rs. 1,785 a share; subscribed 5.71 times.' },
];
