import type { StaticDrill } from './types';

// Static drills for Parts C to F (corporate finance, private equity, venture capital and
// adjacent roles). Every item is grounded in the guide's text, tables and worked examples.
export const TRACK_DRILLS: StaticDrill[] = [
  // ================= Corporate finance =================
  // CF-01 Function map
  { id: 'cf01a', topic: 'CF-01', kind: 'mcq', q: 'Which team owns accounting, the month-end close, statutory reporting and internal controls?', options: ['Controllership', 'FP&A', 'Treasury', 'Internal audit'], answer: 0, why: 'Controllership keeps the books and controls honest; its outputs go to auditors, the audit committee and FP&A.', tags: [null, 'concept', 'concept', 'concept'] },
  { id: 'cf01b', topic: 'CF-01', kind: 'sort', q: 'Which team owns each output?', buckets: ['FP&A', 'Treasury', 'Controllership', 'Investor relations'], items: [['Annual operating plan and monthly outlook', 0], ['Variance commentary and the MBR pack', 0], ['Cash forecast and debt raises', 1], ['FX hedging and investing surplus cash', 1], ['Monthly books and quarterly results', 2], ['Annual report and audit', 2], ['Earnings calls and guidance', 3]], why: 'FP&A plans and explains, treasury funds and protects, controllership records and reports, IR speaks to the market.' },
  { id: 'cf01c', topic: 'CF-01', kind: 'mcq', q: 'To stay independent, internal audit reports its findings to:', options: ['The audit committee', 'The CFO', 'FP&A', 'The statutory auditor'], answer: 0, why: 'Internal audit tests controls and processes independently and reports to the audit committee.' },

  // CF-18 Operating cadence
  { id: 'cf18a', topic: 'CF-18', kind: 'order', q: 'An interviewer asks you to trace an AOP assumption through to a management decision. Put the chain in order.', items: ['Assumption', 'Budget', 'Monthly actual', 'Variance', 'Explanation', 'Action', 'Reforecast'], why: 'Business owners propose assumptions, finance challenges them, and every month actuals are compared, explained, acted on and rolled into the forecast.' },
  { id: 'cf18b', topic: 'CF-18', kind: 'mcq', q: 'For an April-to-March company, when is the annual operating plan built and approved?', options: ['January to March, approved by the board before April', 'October to December, with the long-range plan', 'April to June, after the year starts', 'After the first quarter results'], answer: 0, why: 'Strategy and the long-range plan run October to December; the AOP follows January to March and is approved before the year begins.' },
  { id: 'cf18c', topic: 'CF-18', kind: 'mcq', q: 'Who approves the AOP, major capex, M&A and funding?', options: ['The board', 'The CFO alone', 'FP&A', 'Business unit heads'], answer: 0, why: 'Owners propose, finance challenges, the CFO and CEO approve, and the board approves the AOP and the big capital decisions.' },
  { id: 'cf18d', topic: 'CF-18', kind: 'mcq', q: 'How often does FP&A typically re-forecast the full year in a rolling forecast?', options: ['Quarterly', 'Once a year', 'Daily', 'Only when the board asks'], answer: 0, why: 'The rolling forecast is updated quarterly and often covers the next four quarters; the monthly outlook updates the current year.' },

  // CF-17 Career variants
  { id: 'cf17a', topic: 'CF-17', kind: 'sort', q: 'What does each corporate finance seat emphasise in interviews?', buckets: ['FP&A / business finance', 'Treasury', 'Controllership', 'Corporate development'], items: [['Variance analysis and driver-based planning', 0], ['Pricing and mix, stakeholder handling', 0], ['Cash forecasting, FX hedging, rates view', 1], ['Ind AS, close process, audit', 2], ['Valuation, M&A process, strategic logic', 3]], why: 'Read the job description: a "finance manager" at a consumer MNC and one at a startup test very different things.' },
  { id: 'cf17b', topic: 'CF-17', kind: 'mcq', q: 'A finance leadership programme (CFO track) interview emphasises:', options: ['Breadth: business judgement, communication, a case, basic accounting and valuation', 'Deep derivatives pricing', 'Only Ind AS technicalities', 'A full LBO model'], answer: 0, why: 'Leadership programmes rotate hires through FP&A, treasury, plant finance and M&A, so they test breadth and judgement.' },
  { id: 'cf17c', topic: 'CF-17', kind: 'mcq', q: 'In a CFO-track business partner case, what does strong performance show?', options: ['An issue tree, quantified drivers and a recommendation with trade-offs', 'Recall of every accounting standard', 'A precise answer without assumptions', 'A long list of possible causes'], answer: 0, why: 'The case is an ambiguous operating problem with missing data; structure, numbers and a clear recommendation win.' },

  // CF-02 Plans and forecasts
  { id: 'cf02a', topic: 'CF-02', kind: 'sort', q: 'Match each description to the plan it belongs to.', buckets: ['Strategic plan', 'AOP (budget)', 'Rolling forecast', 'Monthly outlook'], items: [['3 to 5 years, top-down, few drivers', 0], ['Common failure: hockey-stick optimism', 0], ['Targets, resource allocation, incentives', 1], ['Common failure: sandbagging', 1], ['Next 4 to 6 quarters, updated quarterly', 2], ['Common failure: treated as a second budget', 2], ['Latest view of the current year, updated monthly', 3], ['Common failure: anchored on the budget', 3]], why: 'Each plan has a different horizon and purpose, and a characteristic way of going wrong.' },
  { id: 'cf02b', topic: 'CF-02', kind: 'mcq', q: 'Which is driver-based planning?', options: ['Revenue = outlets × throughput × price; staff cost = headcount × cost per head', 'Last year\'s revenue plus 8%', 'The CEO\'s target divided equally across units', 'The average of three analyst forecasts'], answer: 0, why: 'Building from operating drivers makes forecasts explainable and scenarios quick.', tags: [null, 'concept', 'concept', 'concept'] },
  { id: 'cf02c', topic: 'CF-02', kind: 'mcq', q: 'What is sandbagging?', options: ['Setting targets low so they are easy to beat', 'Hiding costs in the next year', 'Over-optimistic long-range plans', 'Delaying the monthly close'], answer: 0, why: 'It is the classic AOP failure because targets drive incentives.' },

  // CF-03 Variance analysis
  { id: 'cf03a', topic: 'CF-03', kind: 'mcq', q: 'Which is the correct price variance?', options: ['Σ (Actual price − Budget price) × Actual units', 'Σ (Actual price − Budget price) × Budget units', '(Actual units − Budget units) × Budget price', 'Actual revenue − Budget revenue'], answer: 0, why: 'Price is measured on what you actually sold; volume uses the budget average price; mix uses budget prices on the shifted mix.', tags: [null, 'mix_price', 'concept', 'concept'] },
  { id: 'cf03b', topic: 'CF-03', kind: 'mcq', q: 'Revenue is flat against budget: volume +4.2, mix −5.2, price +0.9 (Rs. crore). What is the headline for the CFO?', options: ['A shift towards the lower-priced pack offset higher volumes', 'Pricing failed', 'Volumes missed budget', 'Nothing happened: revenue was on budget'], answer: 0, why: 'Flat totals can hide large offsetting drivers; name the driver, the cause, the consequence and the action.' },
  { id: 'cf03c', topic: 'CF-03', kind: 'multi', q: 'What must a CFO-grade variance commentary contain?', options: ['The driver, with a number', 'The cause', 'The consequence for the full-year forecast', 'The action being taken', 'A list of every GL line that moved'], answers: [0, 1, 2, 3], why: 'The guide\'s model sentence names driver, cause, consequence and action in one line.' },
  { id: 'cf03d', topic: 'CF-03', kind: 'sort', q: 'Classify each cost variance.', buckets: ['Timing', 'Permanent run-rate', 'One-off'], items: [['A marketing campaign moved from June to July', 0], ['A planned maintenance shutdown slipped a month', 0], ['A company-wide salary increase above plan', 1], ['A competitor launch that cut premium volumes for the year', 1], ['A litigation settlement booked this quarter', 2], ['A one-time IPO readiness fee', 2]], why: 'Always separate timing from permanent variances, and one-offs from run-rate changes; they lead to different forecast updates.' },
  { id: 'cf03e', topic: 'CF-03', kind: 'mcq', q: 'Staff costs are over budget. Which split explains them?', options: ['Headcount variance and rate (cost per head) variance', 'Price and mix variance', 'Volume and timing variance', 'Usage and yield variance'], answer: 0, why: 'For people costs, separate the number of people from what each costs; for materials, usage from price.' },

  // CF-04 Scenarios and forecast accuracy
  { id: 'cf04a', topic: 'CF-04', kind: 'sort', q: 'Scenario or sensitivity?', buckets: ['Scenario', 'Sensitivity'], items: [['Monsoon failure: lower rural volumes, higher input costs and delayed price rises together', 0], ['Recession case with lower volumes, weaker pricing and slower collections', 0], ['A 1% rupee depreciation', 1], ['A 5% rise in crude', 1], ['A 10-day increase in receivable days', 1]], why: 'A scenario combines consistent assumptions; a sensitivity moves one driver.' },
  { id: 'cf04b', topic: 'CF-04', kind: 'mcq', q: 'A sales team\'s forecasts are too high almost every month. What is this, and what does it suggest?', options: ['Bias; it tells you something about incentives', 'Low MAPE; the team is accurate', 'Random error; ignore it', 'A timing variance'], answer: 0, why: 'Track both the size of the error (MAPE) and its direction (bias). Persistent bias usually has an incentive behind it.' },

  // CF-05 ZBB
  { id: 'cf05a', topic: 'CF-05', kind: 'mcq', q: 'Where is zero-based budgeting most useful?', options: ['Overheads such as marketing, travel, IT and admin in a cost programme', 'A stable, well-run cost base', 'Raw material purchases', 'Statutory audit fees'], answer: 0, why: 'ZBB challenges legacy costs and links spend to value; it is associated with consumer goods and PE-owned cost programmes.' },
  { id: 'cf05b', topic: 'CF-05', kind: 'sort', q: 'Which budgeting method has each weakness?', buckets: ['Incremental budgeting', 'Zero-based budgeting'], items: [['Locks in inefficiency', 0], ['Encourages "use it or lose it"', 0], ['Time-consuming', 1], ['Can damage capability if applied bluntly', 1]], why: 'In interviews, show you understand both the power of ZBB and its cost.' },

  // CF-06 Management reporting
  { id: 'cf06a', topic: 'CF-06', kind: 'mcq', q: 'What belongs on page one of a monthly business review pack?', options: ['Headline performance against budget and last year, the three things that matter, decisions needed', 'The full trial balance', 'Every KPI for every business', 'The auditor\'s management letter'], answer: 0, why: 'A good MBR pack fits on a few pages and starts with a one-page summary that drives decisions.' },
  { id: 'cf06b', topic: 'CF-06', kind: 'multi', q: 'What does a board pack add to the monthly management pack?', options: ['Strategy progress', 'Capital projects', 'Funding', 'Governance items', 'Daily SKU-level sales'], answers: [0, 1, 2, 3], why: 'Boards look at direction, capital and governance, not operating detail.' },

  // CF-07 Pricing and profitability
  { id: 'cf07a', topic: 'CF-07', kind: 'mcq', q: 'Why compare pricing options on contribution rather than on net profit?', options: ['Fixed costs do not change with a pricing decision in the short run', 'Net profit is not audited', 'Contribution includes tax', 'Contribution is always higher'], answer: 0, why: 'Contribution margin (price minus variable cost) is the unit of analysis for pricing.' },
  { id: 'cf07b', topic: 'CF-07', kind: 'mcq', q: 'At a 40% contribution margin, how much extra volume does a 5% price cut need just to keep contribution flat?', options: ['14.3%', '12.5%', '5.0%', '11.1%'], answer: 0, why: 'Needed gain = cut ÷ (margin − cut) = 5 ÷ 35 = 14.3%. 11.1% is the loss a 5% increase can absorb.', tags: [null, 'concept', 'concept', 'concept'] },
  { id: 'cf07c', topic: 'CF-07', kind: 'mcq', q: 'A fast-growing channel looks attractive on gross margin. What test decides whether it is really profitable?', options: ['Allocate cost-to-serve: discounts, trade spend, logistics, credit days, returns', 'Compare its revenue growth with the company average', 'Check its share of total volume', 'Look at its gross margin only'], answer: 0, why: 'General trade, modern trade, e-commerce and quick commerce have very different trade spend and credit terms.' },

  // CF-08 Capex and make-or-buy
  { id: 'cf08a', topic: 'CF-08', kind: 'order', q: 'Put the capex approval process in order.', items: ['Business case: strategic rationale, demand, capacity', 'Financial evaluation: NPV, IRR, payback, sensitivities', 'Risks and alternatives', 'Approval at the right level', 'Execution', 'Post-investment review against the approved case'], why: 'The post-investment review closes the loop and keeps future business cases honest.' },
  { id: 'cf08b', topic: 'CF-08', kind: 'mcq', q: 'A Rs. 120 crore line returns 25, 32 and 38 in years 1 to 3, then 40 a year. What is the simple payback?', options: ['About 3.6 years', 'About 3.0 years', 'About 4.2 years', 'About 2.8 years'], answer: 0, why: 'Cumulative cash is 95 after three years; the remaining 25 of year 4\'s 40 is 0.6 of a year.', tags: [null, 'arithmetic', 'arithmetic', 'arithmetic'] },
  { id: 'cf08c', topic: 'CF-08', kind: 'multi', q: 'Which strategic factors often decide a make-or-buy choice?', options: ['Control of quality or intellectual property', 'Supplier concentration', 'Flexibility', 'The colour of the product packaging'], answers: [0, 1, 2], why: 'Compare incremental cost of making with buying, then weigh control, concentration and flexibility.' },

  // CF-09 Plant and sales finance
  { id: 'cf09a', topic: 'CF-09', kind: 'mcq', q: 'Under absorption costing, what happens if a plant produces more than it sells?', options: ['Fixed overheads go into inventory, so reported profit can rise in the short term', 'Profit falls immediately', 'Nothing: costing does not affect profit', 'Variable costs are capitalised as goodwill'], answer: 0, why: 'Marginal costing avoids this and is better for decisions.' },
  { id: 'cf09b', topic: 'CF-09', kind: 'mcq', q: 'Which inventory cost formula is not permitted under Ind AS 2?', options: ['LIFO', 'FIFO', 'Weighted average', 'Specific identification for unique items'], answer: 0, why: 'Weighted average or FIFO; the choice affects margins when input prices move.' },
  { id: 'cf09c', topic: 'CF-09', kind: 'mcq', q: 'In standard costing, what do price, usage, efficiency and volume variances show?', options: ['Where the plant is gaining or losing money against standard', 'The tax payable', 'Customer profitability', 'The cost of capital'], answer: 0, why: 'Each product has a standard cost at standard rates and quantities; variances locate the gap.' },

  // CF-10 Cash forecasting and working capital
  { id: 'cf10a', topic: 'CF-10', kind: 'multi', q: 'A 13-week forecast breaches the minimum cash buffer in weeks 6 to 13. Which are treasury responses?', options: ['Draw on a committed revolving credit facility', 'Issue short-term commercial paper', 'Accelerate collections, including factoring through TReDS', 'Negotiate supplier timing or defer a discretionary payment', 'Cut maintenance capex permanently'], answers: [0, 1, 2, 3], why: 'The forecast exists to give time to act; permanently starving maintenance capex damages the business.' },
  { id: 'cf10b', topic: 'CF-10', kind: 'sort', q: 'Which working capital lever is each action?', buckets: ['Receivables', 'Inventory', 'Payables'], items: [['Tighter credit terms and collections discipline', 0], ['Early-payment discounts to customers', 0], ['Better demand planning', 1], ['SKU rationalisation', 1], ['Supplier terms', 2], ['Supply chain finance', 2]], why: 'Each part of the cycle has its own levers; the cash conversion cycle ties them together.' },
  { id: 'cf10c', topic: 'CF-10', kind: 'mcq', q: 'Under section 43B(h), what happens if a company pays a micro or small supplier later than the MSMED Act limit?', options: ['The expense is not deductible for tax until it is paid', 'Nothing, if the supplier agrees', 'The supplier pays a penalty', 'The company must report it to SEBI'], answer: 0, why: 'The limit is 45 days with an agreement; this changed payables management across Indian companies from FY24. Check the current rules before quoting them.' },
  { id: 'cf10d', topic: 'CF-10', kind: 'order', q: 'A board-approved investment policy for surplus cash ranks objectives in which order?', items: ['Safety', 'Liquidity', 'Yield'], why: 'Surplus cash goes into bank deposits, liquid and overnight funds, commercial paper and T-bills: safety first, then liquidity, then yield.' },

  // CF-11 Debt, covenants and FX
  { id: 'cf11a', topic: 'CF-11', kind: 'sort', q: 'Which type of FX risk is each?', buckets: ['Transaction', 'Translation', 'Economic'], items: [['A dollar payable due in three months', 0], ['A euro receivable from an export order', 0], ['Consolidating a foreign subsidiary\'s balance sheet', 1], ['Losing competitiveness when the rupee strengthens against a rival\'s currency', 2]], why: 'Forwards and options hedge transaction exposure; natural hedges match dollar costs with dollar revenues.' },
  { id: 'cf11b', topic: 'CF-11', kind: 'mcq', q: 'A floating-rate borrower expects rates to rise. Which swap protects it?', options: ['Pay fixed, receive floating', 'Receive fixed, pay floating', 'A currency swap', 'No swap: floating benefits from rising rates'], answer: 0, why: 'Paying fixed locks the cost; the floating leg received offsets the loan\'s floating interest.', tags: [null, 'concept', 'concept', 'concept'] },
  { id: 'cf11c', topic: 'CF-11', kind: 'mcq', q: 'The three-month forward rupee rate is above spot. What does the forward premium tell you?', options: ['The interest rate differential between rupee and dollar', 'The market expects the rupee to fall by that much', 'The bank\'s margin', 'The RBI\'s target rate'], answer: 0, why: 'The forward is set by interest rate parity; it is not a forecast.' },
  { id: 'cf11d', topic: 'CF-11', kind: 'mcq', q: 'Net debt is Rs. 600 crore, EBITDA Rs. 250 crore and the covenant is 3.0x. How far can EBITDA fall before a breach?', options: ['20%', '17%', '25%', '40%'], answer: 0, why: 'Breach EBITDA = 600 ÷ 3.0 = 200, a 20% fall from 250. Report headroom monthly and negotiate waivers early.', tags: [null, 'arithmetic', 'arithmetic', 'concept'] },

  // CF-12 Close and controls
  { id: 'cf12a', topic: 'CF-12', kind: 'order', q: 'Put the month-end close in order.', items: ['Sub-ledgers closed; bank reconciliations', 'Accruals, provisions, intercompany reconciliations', 'Consolidation, eliminations, FX translation', 'Flash results; variance review with FP&A', 'Management pack; CFO review'], why: 'A typical close runs working days 1 to 10.' },
  { id: 'cf12b', topic: 'CF-12', kind: 'mcq', q: 'Under SEBI LODR, quarterly results for listed companies are due within:', options: ['45 days of quarter end (60 days for the fourth quarter and annual results)', '30 days for every quarter', '90 days', '15 days'], answer: 0, why: 'They are approved by the audit committee and board, with a limited review or audit. Check the current regulation before quoting it.' },
  { id: 'cf12c', topic: 'CF-12', kind: 'mcq', q: 'How would you detect "revenue booked but not delivered"?', options: ['Reconcile invoices with dispatch records and customer confirmations; check credit notes after period end', 'Compare revenue with last year', 'Ask the sales team', 'Check the bank balance only'], answer: 0, why: 'Controls cover authorisation, segregation of duties, reconciliations, system access and review.' },

  // CF-13 Ind AS
  { id: 'cf13a', topic: 'CF-13', kind: 'sort', q: 'Match the standard to its subject.', buckets: ['Ind AS 115', 'Ind AS 116', 'Ind AS 109', 'Ind AS 36', 'Ind AS 102'], items: [['Revenue: performance obligations, principal versus agent', 0], ['Leases: ROU asset and lease liability', 1], ['Financial instruments: expected credit loss, hedge accounting', 2], ['Impairment: annual goodwill testing', 3], ['Share-based payment: ESOP expense', 4]], why: 'These are the standards that come up most in corporate finance and CA interviews.' },
  { id: 'cf13b', topic: 'CF-13', kind: 'mcq', q: 'How did Ind AS 116 change reported EBITDA and net debt for airlines and retailers?', options: ['Both rose: rent moved out of opex into depreciation and interest, and lease liabilities joined debt', 'Both fell', 'EBITDA fell, net debt rose', 'No change'], answer: 0, why: 'Always end with the business consequence: KPIs, covenants, bonuses or valuation.' },

  // CF-14 Statutory reporting and governance
  { id: 'cf14a', topic: 'CF-14', kind: 'mcq', q: 'Segment reporting under Ind AS 108 follows:', options: ['How the chief operating decision maker reviews the business', 'Legal entities', 'Tax jurisdictions', 'Whatever the auditor prefers'], answer: 0, why: 'Investors use segments to value parts of the business separately.' },
  { id: 'cf14b', topic: 'CF-14', kind: 'mcq', q: 'Under LODR, related party transactions need:', options: ['Audit committee approval, and shareholder approval above materiality thresholds', 'Only CFO approval', 'No approval if at arm\'s length', 'RBI approval'], answer: 0, why: 'Promoter-group dealings are a key governance risk in India.' },

  // CF-15 Capital allocation
  { id: 'cf15a', topic: 'CF-15', kind: 'order', q: 'Put the capital allocation discipline in order of priority.', items: ['Fund maintenance capex', 'Fund projects and acquisitions whose risk-adjusted returns exceed the cost of capital', 'Keep leverage within the target range', 'Return the rest through dividends or buybacks'], why: 'Without maintenance capex the business shrinks; surplus cash without a purpose should go back to shareholders.' },
  { id: 'cf15b', topic: 'CF-15', kind: 'mcq', q: 'Which project deserves the higher hurdle rate?', options: ['A new-country entry', 'A capacity expansion in a core product', 'Both the same: use one company WACC', 'Whichever is larger'], answer: 0, why: 'Hurdle rates should differ by risk.' },
  { id: 'cf15c', topic: 'CF-15', kind: 'multi', q: 'Which are common capital allocation failures?', options: ['Empire-building acquisitions', 'Underinvesting in maintenance to flatter free cash flow', 'Hoarding cash without a purpose', 'Buying back shares at any price', 'Returning surplus cash when no project beats the cost of capital'], answers: [0, 1, 2, 3], why: 'Returning genuine surplus is the discipline, not a failure.' },

  // CF-16 Raising equity as the issuer
  { id: 'cf16a', topic: 'CF-16', kind: 'multi', q: 'Which concerns does the CFO have in an equity raise that the banker may not weigh the same way?', options: ['Dilution to existing holders, especially the promoter', 'Signalling: raising when the stock looks expensive can read as a sell signal', 'Use of proceeds', 'Credibility of guidance after the raise', 'Maximising the underwriting fee'], answers: [0, 1, 2, 3], why: 'The CFO owns the equity story: why this company, why now, what the money is for.' },

  // ================= Private equity =================
  // PE-01 Fund economics
  { id: 'pe01a', topic: 'PE-01', kind: 'mcq', q: 'A common PE management fee is:', options: ['About 2% of committed capital in the investment period, then on invested capital', '20% of profits', '2% of the fund\'s profits', 'A fixed Rs. 1 crore a year'], answer: 0, why: 'Carried interest (commonly 20% above an 8% hurdle) is the other income stream.', tags: [null, 'concept', 'concept', 'concept'] },
  { id: 'pe01b', topic: 'PE-01', kind: 'order', q: 'Put a European waterfall in order.', items: ['Return of capital to LPs', 'Preferred return to LPs (hurdle)', 'GP catch-up', '80/20 split of the rest'], why: 'With a full catch-up the GP ends with exactly 20% of the fund\'s profit.' },
  { id: 'pe01c', topic: 'PE-01', kind: 'mcq', q: 'How does an American (deal-by-deal) waterfall differ from a European one?', options: ['It pays carry earlier, protected by a clawback if later deals lose money', 'It has no hurdle', 'It pays LPs first on every deal forever', 'It is illegal in India'], answer: 0, why: 'European waterfalls return the whole fund\'s capital and hurdle before carry.' },
  { id: 'pe01d', topic: 'PE-01', kind: 'sort', q: 'Match each LP measure to its definition.', buckets: ['IRR', 'MOIC / TVPI', 'DPI', 'PME'], items: [['Time-weighted annual return', 0], ['Total value ÷ paid-in capital', 1], ['Distributions ÷ paid-in: cash actually returned', 2], ['Performance against a public market index', 3]], why: 'A high IRR with a low DPI has not yet proved its marks in cash.' },
  { id: 'pe01e', topic: 'PE-01', kind: 'sort', q: 'Which strategy is each?', buckets: ['Buyout', 'Growth equity', 'PIPE', 'Private credit'], items: [['Control, often with debt', 0], ['Significant minority stakes in growing, usually profitable companies', 1], ['Stakes in listed companies via preferential allotments or blocks', 2], ['NCDs and mezzanine with equity-like returns', 3]], why: 'Growth equity has been the dominant form of Indian PE for two decades; buyouts are growing.' },

  // PE-15 Operating model
  { id: 'pe15a', topic: 'PE-15', kind: 'mcq', q: 'Who commits capital to a fund for about ten years and has it drawn down through capital calls?', options: ['Limited partners', 'The general partner', 'Portfolio companies', 'Lenders'], answer: 0, why: 'LPs (pension funds, insurers, sovereigns, family offices, funds of funds) commit; the GP invests.' },
  { id: 'pe15b', topic: 'PE-15', kind: 'mcq', q: 'Most domestic Indian PE and private debt funds are registered with SEBI as:', options: ['Category II AIFs', 'Category I AIFs', 'Category III AIFs', 'Mutual funds'], answer: 0, why: 'Category I covers venture, angel, SME, social impact and infrastructure; Category III covers hedge-fund-like strategies.' },

  // PE-16 Roles
  { id: 'pe16a', topic: 'PE-16', kind: 'sort', q: 'Who does what in a PE firm?', buckets: ['Partners', 'Associates', 'Operating partners', 'Investment committee'], items: [['Raise funds, source and sponsor deals, sit on boards', 0], ['Models, market work, IC memo drafting, portfolio monitoring', 1], ['Functional experts who drive value creation', 2], ['Approve spending on diligence and final investments', 3]], why: 'Associates are the usual MBA entry point.' },

  // PE-14 Firm fit
  { id: 'pe14a', topic: 'PE-14', kind: 'sort', q: 'Classify each investor.', buckets: ['Global mega-fund', 'Sovereign / pension investing directly', 'India-focused mid-market fund', 'Family office / evergreen'], items: [['Blackstone', 0], ['KKR', 0], ['Temasek', 1], ['CPP Investments', 1], ['ChrysCapital', 2], ['Kedaara Capital', 2], ['Premji Invest', 3]], why: 'Know the fund\'s size, sectors, cheque size, control versus minority, and recent deals.' },
  { id: 'pe14b', topic: 'PE-14', kind: 'multi', q: 'For each target fund, what firm research do interviewers notice?', options: ['Fund size and vintage', 'Sectors and cheque size', 'Three recent investments and one exit', 'Your view on one portfolio company', 'The fund\'s office address'], answers: [0, 1, 2, 3], why: '"Which one would you invest in, which would you not?" is a common question.' },

  // PE-02 Thesis and sourcing
  { id: 'pe02a', topic: 'PE-02', kind: 'mcq', q: 'Proprietary deals versus auctions:', options: ['Proprietary deals are cheaper but slower; auctions are faster but price-competitive', 'Auctions are always cheaper', 'Proprietary deals are illegal in India', 'There is no difference in price'], answer: 0, why: 'Relationships with promoters are the most valuable sourcing channel.' },
  { id: 'pe02b', topic: 'PE-02', kind: 'mcq', q: 'What is an investment thesis?', options: ['A one-paragraph argument for why a type of company will compound, and at what price you would buy', 'A list of every company in a sector', 'The fund\'s legal documents', 'A valuation spreadsheet'], answer: 0, why: 'From the thesis comes a target universe mapped by size, growth, profitability and ownership.' },

  // PE-17 Funnel
  { id: 'pe17a', topic: 'PE-17', kind: 'order', q: 'Put the buyout process in order.', items: ['Source', 'Screen', 'Preliminary IC', 'Offer / LOI', 'Due diligence', 'Final IC', 'Sign and close', 'Own and improve', 'Exit'], why: 'IC gates sit where serious money is committed: before diligence spend and before signing.' },
  { id: 'pe17b', topic: 'PE-17', kind: 'mcq', q: 'In the guide\'s illustrative funnel, how many of 100 companies reviewed end up as investments?', options: ['About 1', 'About 12', 'About 35', 'About 6'], answer: 0, why: '100 reviewed, 35 meetings, 12 preliminary IC memos, 6 offers, 3 full diligences, 1 investment.' },

  // PE-03 Commercial DD
  { id: 'pe03a', topic: 'PE-03', kind: 'mcq', q: 'What is the most important question in commercial diligence?', options: ['What evidence would prove this thesis wrong?', 'How fast can we sign?', 'What multiple did the last deal get?', 'How many slides does the CIM have?'], answer: 0, why: 'The best diligence tries to disprove the thesis, not confirm it.' },
  { id: 'pe03b', topic: 'PE-03', kind: 'multi', q: 'Customer diligence checks:', options: ['Concentration (top 10 customers\' share)', 'Retention and churn', 'Pricing power and switching costs', 'The founder\'s alma mater'], answers: [0, 1, 2], why: 'Customer calls and surveys are the core evidence.' },

  // PE-04 QoE
  { id: 'pe04a', topic: 'PE-04', kind: 'sort', q: 'How does each item adjust reported EBITDA in a QoE?', buckets: ['Add back', 'Deduct'], items: [['Genuinely one-off restructuring cost', 0], ['IPO costs that will not recur', 0], ['Promoter\'s family salaries above market that will stop', 0], ['Rent paid to a promoter entity below market', 1], ['Aggressive revenue recognition', 1], ['Under-provisioned receivables', 1]], why: 'QoE bridges reported EBITDA to the sustainable run-rate on which price is based.' },
  { id: 'pe04b', topic: 'PE-04', kind: 'multi', q: 'Which are debt-like items that reduce the equity price?', options: ['Unpaid statutory dues', 'Gratuity shortfalls', 'Earn-outs from past acquisitions', 'Tax exposures', 'Trade payables within normal terms'], answers: [0, 1, 2, 3], why: 'Normal payables sit in the working capital peg, not in debt.' },
  { id: 'pe04c', topic: 'PE-04', kind: 'mcq', q: 'What is the net working capital peg?', options: ['A "normal" NWC level; the price adjusts if closing NWC differs', 'The maximum debt allowed', 'A fixed price for inventory', 'The seller\'s minimum cash balance'], answer: 0, why: 'It is often a 12-month average adjusted for seasonality and growth.' },

  // PE-11 Management, legal, tax, structure
  { id: 'pe11a', topic: 'PE-11', kind: 'mcq', q: 'How do foreign investors protect the downside in India, given FEMA?', options: ['Through valuation adjustments and preference terms, since guaranteed returns are not allowed', 'With a guaranteed buyback at a fixed return', 'By lending instead of investing', 'They cannot protect it at all'], answer: 0, why: 'Instruments like CCPS and structured terms replace assured exits.' },
  { id: 'pe11b', topic: 'PE-11', kind: 'sort', q: 'Governance right or exit right?', buckets: ['Governance right', 'Exit right'], items: [['Board seat', 0], ['Affirmative vote on budgets and acquisitions', 0], ['Information rights', 0], ['IPO within a set period', 1], ['Drag-along', 1], ['Tag-along', 1]], why: 'Minority investors rely on both to influence the company and get out.' },

  // PE-05 Sources and uses
  { id: 'pe05a', topic: 'PE-05', kind: 'mcq', q: 'EBITDA Rs. 100 crore, bought at 10x, fees Rs. 20 crore, debt 5x EBITDA. How much equity does the sponsor put in?', options: ['Rs. 520 crore', 'Rs. 500 crore', 'Rs. 480 crore', 'Rs. 1,020 crore'], answer: 0, why: 'Equity = EV + fees − debt = 1,000 + 20 − 500 = 520.', tags: [null, 'concept', 'arithmetic', 'concept'] },
  { id: 'pe05b', topic: 'PE-05', kind: 'mcq', q: 'Which debt tranche is usually the cheapest?', options: ['Senior secured term loan', 'Mezzanine', 'Second lien', 'PIK notes'], answer: 0, why: 'Senior secured debt amortises and carries maintenance covenants; each tranche\'s cost and security set how much leverage the business can carry.' },

  // PE-06 Debt schedule and exit
  { id: 'pe06a', topic: 'PE-06', kind: 'mcq', q: 'Year 1: net income 28.5, D&A 22, capex 22, increase in NWC 2.5. How much free cash flow repays debt?', options: ['26.0', '28.5', '50.5', '31.0'], answer: 0, why: 'FCF = 28.5 + 22 − 22 − 2.5 = 26.0, all swept to repay debt.', tags: [null, 'wc_sign', 'dep_as_cash', 'wc_sign'] },
  { id: 'pe06b', topic: 'PE-06', kind: 'mcq', q: 'Exit equity of Rs. 1,337 crore on entry equity of Rs. 520 crore over five years gives an IRR of about:', options: ['20.8%', '31.4%', '25.7%', '15.0%'], answer: 0, why: 'MOIC = 2.57x; IRR = 2.57^(1/5) − 1 = 20.8%. Dividing the gain by years (31.4%) overstates it.', tags: [null, 'moic_irr', 'arithmetic', 'arithmetic'] },

  // PE-07 Returns drivers
  { id: 'pe07a', topic: 'PE-07', kind: 'mcq', q: 'Which lever does the sponsor control most directly?', options: ['Entry price', 'Exit multiple', 'Interest rates', 'Market growth'], answer: 0, why: 'Buying at 9x instead of 10x lifts IRR by about 5 points in the guide\'s example.' },
  { id: 'pe07b', topic: 'PE-07', kind: 'mcq', q: 'Which rule of thumb is right?', options: ['2x in 3 years ≈ 26% IRR', '2x in 5 years ≈ 26% IRR', '3x in 5 years ≈ 15% IRR', '2.5x in 5 years ≈ 30% IRR'], answer: 0, why: '2x in 5 years ≈ 15%, 2.5x in 5 ≈ 20%, 3x in 5 ≈ 25%.', tags: [null, 'moic_irr', 'moic_irr', 'moic_irr'] },
  { id: 'pe07c', topic: 'PE-07', kind: 'multi', q: 'What does the entry and exit multiple grid teach?', options: ['Never underwrite multiple expansion', 'Leverage amplifies both ways', 'The same MOIC over a longer hold means a lower IRR', 'Higher entry prices raise IRR'], answers: [0, 1, 2], why: 'Build the base case at an exit multiple equal to or below entry.' },
  { id: 'pe07d', topic: 'PE-07', kind: 'mcq', q: 'What makes a good LBO candidate?', options: ['Stable, predictable cash flow, low capex, pricing power and a clear exit', 'High growth that needs heavy capex', 'A new hospital ramping up occupancy', 'A cyclical business at peak margins'], answer: 0, why: 'Debt is repaid from cash flow, so the cash must be there early and reliably.' },

  // PE-08 Growth equity
  { id: 'pe08a', topic: 'PE-08', kind: 'mcq', q: 'A fund invests Rs. 300 crore of primary capital at a Rs. 1,200 crore pre-money. What stake does it get?', options: ['20%', '25%', '30%', '15%'], answer: 0, why: 'Post-money = 1,500; stake = 300 ÷ 1,500 = 20%. Dividing by the pre-money gives 25%.', tags: [null, 'concept', 'arithmetic', 'arithmetic'] },
  { id: 'pe08b', topic: 'PE-08', kind: 'mcq', q: 'What is the standard instrument for Indian growth equity and VC?', options: ['CCPS (compulsorily convertible preference shares)', 'Ordinary shares only', 'Bank loans', 'Warrants'], answer: 0, why: 'CCPS convert to equity and carry a liquidation preference and investor rights.' },
  { id: 'pe08c', topic: 'PE-08', kind: 'mcq', q: 'Where do growth equity returns mainly come from?', options: ['Earnings growth and the exit multiple', 'Debt paydown', 'Management fees', 'Dividend recaps'], answer: 0, why: 'There is little or no debt paydown in a minority growth deal.' },

  // PE-09 Deal sequence
  { id: 'pe09a', topic: 'PE-09', kind: 'order', q: 'Put the deal sequence in order.', items: ['NDA', 'Indication of interest', 'Preliminary IC', 'Term sheet / LOI', 'Due diligence', 'Final IC', 'SPA / SHA', 'Conditions precedent and closing'], why: 'The SPA and SHA are the binding documents; approvals such as CCI come before closing.' },
  { id: 'pe09b', topic: 'PE-09', kind: 'mcq', q: 'What does a PE term sheet or LOI usually make binding?', options: ['Exclusivity', 'The price', 'The closing date', 'Nothing at all'], answer: 0, why: 'Price is usually not binding until the definitive agreements are signed.' },

  // PE-10 IC memo
  { id: 'pe10a', topic: 'PE-10', kind: 'mcq', q: 'What comes first in an IC memo?', options: ['The recommendation: invest X for Y% at Z, with base, upside and downside returns', 'Company history', 'The market overview', 'Open diligence items'], answer: 0, why: 'Answer first; the committee wants the ask and the returns before the story.' },
  { id: 'pe10b', topic: 'PE-10', kind: 'mcq', q: 'Your IC memo must include three things that would make you walk away. Why?', options: ['A pitch with no downside case is a common trap', 'Committees like long memos', 'It is a legal requirement', 'It lowers the price automatically'], answer: 0, why: 'Expect the interviewer to push on the weakest assumption.' },

  // PE-12 Value creation
  { id: 'pe12a', topic: 'PE-12', kind: 'mcq', q: 'Which value creation levers should the base case rest on?', options: ['Revenue growth, margin expansion and cash release', 'Multiple expansion', 'Refinancing at lower rates', 'A favourable IPO window'], answer: 0, why: 'Levers 1 to 3 are operational and repeatable; capital structure depends on credit markets and multiple expansion is partly luck.' },
  { id: 'pe12b', topic: 'PE-12', kind: 'multi', q: 'What goes into a 100-day plan?', options: ['Governance: board, committees, reporting', 'Key hires such as a CFO', 'Quick wins in procurement, pricing and working capital', 'A monthly KPI pack', 'Planning the exit roadshow'], answers: [0, 1, 2, 3], why: 'The 100-day plan turns the thesis into actions immediately after closing.' },
  { id: 'pe18a', topic: 'PE-18', kind: 'mcq', q: 'How can a fund return cash early without selling?', options: ['Refinancing or a dividend recapitalisation', 'Charging higher management fees', 'Delaying capital calls', 'Issuing a new fund'], answer: 0, why: 'Add-on acquisitions can also build a platform at lower multiples than the platform will exit at.' },

  // PE-13 Exits
  { id: 'pe13a', topic: 'PE-13', kind: 'sort', q: 'Match the exit route to its watch-out.', buckets: ['IPO', 'Strategic sale', 'Sponsor-to-sponsor', 'Continuation vehicle'], items: [['Partial exit only; lock-ins; market timing', 0], ['Regulatory approvals; narrow buyer universe', 1], ['The next buyer needs its own upside', 2], ['Conflicts; needs LP consent and a fair price', 3]], why: 'India\'s deep IPO market has made listings a frequent PE exit.' },

  // ================= Venture capital =================
  // VC-01 Fund math
  { id: 'vc01a', topic: 'VC-01', kind: 'mcq', q: 'A Rs. 1,000 crore fund owns 10% of its companies at exit. How big must one exit be to return the fund?', options: ['Rs. 10,000 crore', 'Rs. 1,000 crore', 'Rs. 3,000 crore', 'Rs. 30,000 crore'], answer: 0, why: '1,000 ÷ 10% = 10,000 crore, roughly a US$1 billion outcome. Rs. 30,000 crore is the whole portfolio needed for 3x.', tags: [null, 'concept', 'concept', 'concept'] },
  { id: 'vc01b', topic: 'VC-01', kind: 'mcq', q: 'What share of a fund is often kept as reserves for follow-ons?', options: ['40 to 60%', '5 to 10%', 'None', 'All of it'], answer: 0, why: 'Ownership matters as much as picking: finding the outlier at 1% does not return capital.' },
  { id: 'vc01c', topic: 'VC-01', kind: 'mcq', q: 'Why is a business that can reach Rs. 500 crore of value a bad venture investment for a Rs. 1,000 crore fund?', options: ['It cannot return a meaningful part of the fund at typical ownership', 'It is too risky', 'It is not profitable', 'It is too large'], answer: 0, why: 'Returns come from a handful of outliers, so each investment must be able to become very large.' },

  // VC-14 / VC-16 Organisation and decisions
  { id: 'vc14a', topic: 'VC-14', kind: 'sort', q: 'Who does what in a VC firm?', buckets: ['General partners', 'Principals / VPs', 'Associates / analysts', 'Platform team'], items: [['Raise the fund, champion investments, sit on boards', 0], ['Source and run deals, work towards partnership', 1], ['Market maps, first calls, diligence, memos', 2], ['Talent, marketing and customer introductions for portfolio companies', 3]], why: 'Associates are the typical MBA entry point and are judged heavily on sourcing.' },
  { id: 'vc16a', topic: 'VC-16', kind: 'mcq', q: 'How do most VC firms decide?', options: ['A deal lead champions the startup; the partnership or IC decides', 'The associate decides alone', 'LPs vote on each deal', 'The founder chooses the terms'], answer: 0, why: 'The memo, the partner\'s conviction and ownership fit matter as much as the numbers.' },

  // VC-15 / VC-02 Process and sourcing
  { id: 'vc15a', topic: 'VC-15', kind: 'order', q: 'Put the VC investment process in order.', items: ['Thesis', 'Source', 'First call', 'Partner meeting', 'Diligence', 'Partnership decision', 'Term sheet and close', 'Board and support', 'Follow-on or exit'], why: 'Opportunities stop at every gate: thesis mismatch, small market, weak team, poor retention, terms.' },
  { id: 'vc02a', topic: 'VC-02', kind: 'mcq', q: 'Which sourcing channel is usually best?', options: ['Founder referrals', 'Cold inbound decks', 'Press coverage', 'Other funds\' rejects'], answer: 0, why: 'Sourcing is the job; outbound mapping of a sector is the other channel associates are judged on.' },
  { id: 'vc15b', topic: 'VC-15', kind: 'multi', q: 'Why do opportunities stop at a gate?', options: ['Thesis mismatch (stage, sector, cheque size)', 'A market too small to produce an outlier', 'Weak retention or unit economics', 'Terms that make the ownership target impossible', 'The startup is already profitable'], answers: [0, 1, 2, 3], why: 'Or a partner who is not convinced enough to champion it.' },

  // VC-13 Firm fit
  { id: 'vc13a', topic: 'VC-13', kind: 'sort', q: 'Classify each firm.', buckets: ['Multi-stage / early-stage VC', 'Seed specialist', 'Sector specialist', 'Angel platform / accelerator'], items: [['Peak XV Partners', 0], ['Accel', 0], ['Blume Ventures', 1], ['100X.VC', 1], ['Fireside Ventures (consumer brands)', 2], ['Omnivore (agritech)', 2], ['Inflection Point Ventures', 3]], why: 'Bring a startup that fits the fund\'s thesis and that it has not funded yet.' },

  // VC-03 Market
  { id: 'vc03a', topic: 'VC-03', kind: 'mcq', q: 'How should you size a startup\'s market?', options: ['Bottom-up, cross-checked top-down', 'Top-down from a published industry size', 'Using the founder\'s number', 'From the last round\'s valuation'], answer: 0, why: 'If bottom-up and top-down differ by 5x, find out why.', tags: [null, 'concept', 'concept', 'concept'] },
  { id: 'vc03b', topic: 'VC-03', kind: 'mcq', q: 'Clinic software: SOM of Rs. 30 crore revenue, worth about Rs. 300 crore at 10x. What is the venture verdict?', options: ['A good business but not venture scale, unless it can expand into adjacencies', 'A great venture investment', 'Uninvestable at any price', 'Only the valuation matters'], answer: 0, why: 'A Rs. 1,000 crore fund needs Rs. 10,000 crore outcomes; payments, lending, pharmacy or insurance could change that.' },

  // VC-04 Team and product
  { id: 'vc04a', topic: 'VC-04', kind: 'mcq', q: 'A founder says, "We have no competition." How should you read it?', options: ['As a red flag', 'As a strong moat', 'As proof of a new market', 'As irrelevant'], answer: 0, why: 'There are always incumbents, other startups, substitutes or global players entering India.' },
  { id: 'vc04b', topic: 'VC-04', kind: 'multi', q: 'Which are sources of defensibility at scale?', options: ['Network effects', 'Proprietary data', 'Switching costs', 'Scale economics', 'A large seed round'], answers: [0, 1, 2, 3], why: 'Early on, speed is the only moat; ask what moat the company will have at scale.' },

  // VC-05 PMF
  { id: 'vc05a', topic: 'VC-05', kind: 'mcq', q: 'Which retention pattern signals product-market fit?', options: ['Cohort curves that flatten, with newer cohorts retaining better', 'Curves that decay steadily to zero', 'High signups with falling usage', 'Growth that stops when discounts end'], answer: 0, why: 'Also look for organic growth, rising usage per user and improving unit economics.' },
  { id: 'vc05b', topic: 'VC-05', kind: 'sort', q: 'Bought or earned growth?', buckets: ['Bought', 'Earned'], items: [['Heavy discounts', 0], ['Paid marketing spikes', 0], ['Referrals and word of mouth', 1], ['Organic search and repeat use', 1]], why: 'Ask whether growth survives when discounts are removed.' },

  // VC-06 Metrics
  { id: 'vc06a', topic: 'VC-06', kind: 'sort', q: 'Which model is each core metric most tied to?', buckets: ['B2B SaaS', 'Marketplace', 'Consumer app', 'Fintech lending'], items: [['Net revenue retention', 0], ['CAC payback', 0], ['GMV and take rate', 1], ['Liquidity: fill rates, time to match', 1], ['DAU/MAU', 2], ['D1/D7/D30 retention', 2], ['Credit cost and NIM', 3]], why: 'Healthy signals are context-dependent; know the metric before judging the number.' },
  { id: 'vc06b', topic: 'VC-06', kind: 'mcq', q: 'A B2B SaaS company has 105% net revenue retention. Is that good?', options: ['Below the 110%+ the guide treats as healthy; ask about gross retention and segment', 'Excellent for any SaaS business', 'It means churn is zero', 'NRR does not matter at seed'], answer: 0, why: 'Context matters: segment, contract size and gross retention.' },
  { id: 'vc06c', topic: 'VC-06', kind: 'mcq', q: 'What is the burn multiple?', options: ['Net cash burned ÷ net new ARR', 'Cash ÷ monthly burn', 'Growth rate + profit margin', 'CAC ÷ gross profit per month'], answer: 0, why: 'Below 2 is a healthy signal. Cash ÷ burn is runway; growth + margin is the Rule of 40.', tags: [null, 'concept', 'concept', 'concept'] },

  // VC-07 Runway
  { id: 'vc07a', topic: 'VC-07', kind: 'mcq', q: 'When should founders start raising the next round?', options: ['With 12 to 18 months of runway left, having hit milestones', 'When one month of cash is left', 'Right after closing the last round', 'Only when revenue is profitable'], answer: 0, why: 'Investors ask what this round\'s money will buy and what the company will look like when it is spent.' },
  { id: 'vc07b', topic: 'VC-07', kind: 'mcq', q: 'ARPA Rs. 5,000 a month, 80% gross margin, CAC Rs. 90,000, 2% monthly churn. What is the LTV/CAC?', options: ['About 2.2x', 'About 2.8x', 'About 4.4x', 'About 1.1x'], answer: 0, why: 'LTV = 4,000 ÷ 2% = 2,00,000; ÷ 90,000 = 2.2x. On revenue instead of gross profit you get 2.8x.', tags: [null, 'ltv_on_revenue', 'arithmetic', 'arithmetic'] },

  // VC-10 / VC-11 Diligence and memo
  { id: 'vc10a', topic: 'VC-10', kind: 'mcq', q: 'What is "risk falsification" in early-stage diligence?', options: ['Identify the three things that must be true and test each', 'Removing risks from the memo', 'Asking the founder to sign warranties', 'Buying insurance'], answer: 0, why: 'Diligence also covers founder meetings, backchannel references, customer calls, product trial and data room.' },
  { id: 'vc11a', topic: 'VC-11', kind: 'order', q: 'Put the two-page VC memo in order.', items: ['The ask: round, valuation, cheque, ownership', 'The company in one paragraph', 'Why this could be very big', 'Why this team', 'Evidence so far', 'Key risks and what would make us wrong', 'Exit paths', 'Recommendation and conditions'], why: 'When critiquing a deck, check that each slide answers a partner\'s question and the numbers are consistent.' },

  // VC-08 Dilution
  { id: 'vc08a', topic: 'VC-08', kind: 'mcq', q: 'A startup raises Rs. 50 crore at a Rs. 200 crore pre-money. What does the investor own?', options: ['20%', '25%', '15%', '40%'], answer: 0, why: '50 ÷ (200 + 50) = 20%.', tags: [null, 'concept', 'arithmetic', 'arithmetic'] },
  { id: 'vc08b', topic: 'VC-08', kind: 'mcq', q: 'Why do VCs ask for the option pool in the pre-money?', options: ['It shifts the dilution to existing holders and lowers the effective pre-money', 'It is required by law', 'It increases the founders\' stake', 'It has no effect on anyone'], answer: 0, why: 'Founders should compare offers on effective pre-money and size the pool to a hiring plan.', tags: [null, 'concept', 'pool_shuffle', 'concept'] },
  { id: 'vc08c', topic: 'VC-08', kind: 'mcq', q: 'In India, which instrument gives SAFE-like economics?', options: ['Indian variants such as iSAFE, structured as CCPS', 'US SAFEs used directly', 'Ordinary equity', 'Bank guarantees'], answer: 0, why: 'US SAFEs are not directly usable by Indian companies.' },

  // VC-09 Preferences and anti-dilution
  { id: 'vc09a', topic: 'VC-09', kind: 'mcq', q: 'Series A: Rs. 20 crore for 20%, 1x non-participating. Above what exit value does it convert?', options: ['Rs. 100 crore', 'Rs. 20 crore', 'Rs. 50 crore', 'Rs. 200 crore'], answer: 0, why: 'It converts when 20% of the exit exceeds its Rs. 20 crore preference: above Rs. 100 crore.' },
  { id: 'vc09b', topic: 'VC-09', kind: 'mcq', q: 'Which anti-dilution clause is harshest on founders?', options: ['Full ratchet', 'Broad-based weighted average', 'Narrow-based weighted average', 'No anti-dilution'], answer: 0, why: 'Full ratchet drops the old investor\'s conversion price all the way to the new price.' },
  { id: 'vc09c', topic: 'VC-09', kind: 'mcq', q: 'Which matters more in most outcomes, valuation or terms?', options: ['Terms: a higher valuation with a participating 2x preference can leave founders worse off', 'Valuation, always', 'Neither', 'Only the board seat'], answer: 0, why: 'Preferences matter most in modest exits, which are the most common kind.' },

  // VC-12 / VC-17 Follow-ons
  { id: 'vc12a', topic: 'VC-12', kind: 'mcq', q: 'When should a VC double down with reserves?', options: ['When the company is breaking out and the new price still leaves room for a large multiple', 'Whenever the company asks', 'Only in down rounds', 'Never: reserves are for fees'], answer: 0, why: 'Hold when progress is ambiguous; stop when the thesis is broken.' },
  { id: 'vc17a', topic: 'VC-17', kind: 'multi', q: 'After investing, a VC typically:', options: ['Joins the board or observes', 'Helps with hiring and customers', 'Helps with the next round', 'Reviews milestones', 'Runs the company day to day'], answers: [0, 1, 2, 3], why: 'Fund performance is attributed company by company: pick, ownership, follow-on.' },

  // ================= Adjacent roles =================
  // ADJ-01 Consulting and deal advisory
  { id: 'ad01a', topic: 'ADJ-01', kind: 'sort', q: 'What does each practice mostly test in interviews?', buckets: ['Strategy consulting, PE practice', 'Big 4 transaction services', 'Valuation and modelling', 'Restructuring'], items: [['Case interviews, often a PE diligence case', 0], ['Accounting depth and diligence judgement', 1], ['DCF, comps, Ind AS valuation', 2], ['Cash flow, credit, the IBC process', 3]], why: 'Consulting and finance overlap: strategy firms run CDD, Big 4 deal teams do work that looks like banking.' },
  { id: 'ad01b', topic: 'ADJ-01', kind: 'mcq', q: 'What does a Big 4 transaction services team mainly do?', options: ['Financial due diligence, quality of earnings, net debt and working capital analysis', 'Pitch books for IPOs', 'Statutory audit', 'Equity research reports'], answer: 0, why: 'CAs are strongly placed for these roles.' },

  // ADJ-02 Case interviews
  { id: 'ad02a', topic: 'ADJ-02', kind: 'mcq', q: 'What does MECE mean?', options: ['Mutually exclusive, collectively exhaustive', 'Market, economics, competition, execution', 'Most efficient cost estimate', 'Minimum expected cash earnings'], answer: 0, why: 'A MECE structure covers everything once, with no overlaps.' },
  { id: 'ad02b', topic: 'ADJ-02', kind: 'order', q: 'Put the case interview skills in the order you use them.', items: ['Clarify the objective', 'Build a MECE structure', 'Prioritise', 'Do the quick maths', 'Synthesise a recommendation'], why: 'Frameworks are prompts, not scripts.' },
  { id: 'ad02c', topic: 'ADJ-02', kind: 'sort', q: 'Which framework fits each prompt?', buckets: ['Profitability', 'Market entry', 'M&A / PE diligence', 'Pricing'], items: [['Margins fell 4 points this year', 0], ['Should we launch in Indonesia?', 1], ['A fund wants to buy 120 diagnostic labs', 2], ['What should we charge for the new SKU?', 3]], why: 'Pick the structure that answers the question asked, then adapt it.' },

  // ADJ-03 Equity research
  { id: 'ad03a', topic: 'ADJ-03', kind: 'mcq', q: 'What turns a buy recommendation from an opinion into a pitch?', options: ['A variant view with evidence, plus a catalyst', 'A strong brand', 'A low P/E', 'A long report'], answer: 0, why: '"The market believes X, I believe Y, here is my evidence, and here is the event that will prove me right."' },
  { id: 'ad03b', topic: 'ADJ-03', kind: 'sort', q: 'Sell-side or buy-side?', buckets: ['Sell-side research', 'Buy-side'], items: [['Initiation reports and target prices', 0], ['Success measured by investor rankings', 0], ['Clients reached via the broker\'s sales team', 0], ['Portfolio decisions', 1], ['Success measured against the benchmark', 1]], why: 'Both reward accounting skill and the discipline to say what would prove you wrong.' },
  { id: 'ad03c', topic: 'ADJ-03', kind: 'mcq', q: 'Two companies with the same PAT growth trade at different P/Es. Why might that be?', options: ['Differences in return on capital, cash conversion, risk, growth durability and governance', 'The market is always wrong', 'Only because of index inclusion', 'P/E does not depend on anything'], answer: 0, why: 'A question reported from recent ER and buy-side interviews.' },

  // ADJ-04 Portfolio basics
  { id: 'ad04a', topic: 'ADJ-04', kind: 'sort', q: 'Match each measure to its formula.', buckets: ['Sharpe', 'Treynor', "Jensen's alpha"], items: [['(Return − Rf) ÷ volatility', 0], ['(Return − Rf) ÷ beta', 1], ['Actual return − CAPM expected return', 2]], why: 'Sharpe uses total risk; Treynor uses market risk only.' },
  { id: 'ad04b', topic: 'ADJ-04', kind: 'mcq', q: 'What gives Indian equities structural support month after month?', options: ['Monthly SIP inflows into mutual funds', 'RBI equity purchases', 'Mandatory retail allocations', 'Bank deposit rules'], answer: 0, why: 'AMFI publishes monthly flow data.' },

  // ADJ-05 Markets interviews
  { id: 'ad05a', topic: 'ADJ-05', kind: 'mcq', q: 'You expect the RBI to cut rates. In an overnight indexed swap, you want to:', options: ['Receive fixed', 'Pay fixed', 'Do nothing', 'Buy a currency forward'], answer: 0, why: 'The fixed rate you lock will exceed the falling floating rate. Asked in a recent campus interview.', tags: [null, 'concept', 'concept', 'concept'] },
  { id: 'ad05b', topic: 'ADJ-05', kind: 'multi', q: 'What do markets interviews spend time on?', options: ['Your macro views: RBI, inflation, the rupee, yields, oil', 'Derivatives and fixed income basics', 'Mental maths and probability', 'Detailed Ind AS disclosures'], answers: [0, 1, 2], why: 'Preparation cannot be crammed: follow markets daily for weeks.' },
  { id: 'ad05c', topic: 'ADJ-05', kind: 'mcq', q: 'What does a bank treasury manage?', options: ['Liquidity, SLR bond holdings, CRR, the LCR, ALM mismatches and trading books', 'Only the bank\'s own share price', 'Retail branch sales', 'The loan approval committee'], answer: 0, why: 'Bank treasury is a common ISB markets role.' },

  // ADJ-06 Derivatives
  { id: 'ad06a', topic: 'ADJ-06', kind: 'sort', q: 'Match each Greek to what it measures.', buckets: ['Delta', 'Gamma', 'Vega', 'Theta'], items: [['Sensitivity to the underlying price', 0], ['Change in delta', 1], ['Sensitivity to volatility', 2], ['Passage of time', 3]], why: 'Long options are long gamma and vega, and lose theta each day.' },
  { id: 'ad06b', topic: 'ADJ-06', kind: 'mcq', q: 'Put-call parity for European options states:', options: ['C − P = S − PV(K)', 'C + P = S + K', 'C = P for at-the-money options', 'C − P = K − S'], answer: 0, why: 'It links calls, puts, the stock and a bond; a gap is an arbitrage.' },
  { id: 'ad06c', topic: 'ADJ-06', kind: 'mcq', q: 'Delta of an at-the-money call is about:', options: ['0.5', '1.0', '0', '−0.5'], answer: 0, why: 'Delta is the hedge ratio; it moves towards 1 deep in the money.' },

  // ADJ-07 Credit analysis
  { id: 'ad07a', topic: 'ADJ-07', kind: 'sort', q: 'Which of the five Cs is each?', buckets: ['Character', 'Capacity', 'Capital', 'Collateral', 'Conditions'], items: [['Promoter track record and integrity', 0], ['Cash flow to service debt', 1], ['Equity cushion', 2], ['Security', 3], ['Industry and macro', 4]], why: 'Lenders\' upside is capped at interest and fees, so they study everything that could go wrong.' },
  { id: 'ad07b', topic: 'ADJ-07', kind: 'mcq', q: 'When does a loan become a non-performing asset in India?', options: ['After 90 days overdue', 'After 30 days', 'After 60 days', 'After one year'], answer: 0, why: 'SMA-0, 1 and 2 cover 1 to 30, 31 to 60 and 61 to 90 days. Check current RBI rules before quoting them.' },
  { id: 'ad07c', topic: 'ADJ-07', kind: 'mcq', q: 'Gross NPA versus net NPA:', options: ['Gross is before provisions; net is after', 'Gross includes interest; net excludes it', 'They are the same', 'Net is before provisions'], answer: 0, why: 'Provision coverage links the two.' },
  { id: 'ad07d', topic: 'ADJ-07', kind: 'mcq', q: 'TOL/TNW, a favourite of Indian banks, compares:', options: ['Total outside liabilities with tangible net worth', 'Term loans with total net worth', 'Trade payables with net working capital', 'Total operating leverage with tax'], answer: 0, why: 'Below 3x is the typical comfort zone.' },

  // ADJ-08 Project finance
  { id: 'ad08a', topic: 'ADJ-08', kind: 'sort', q: 'Who bears each project risk by contract?', buckets: ['EPC contractor', 'O&M operator', 'Offtaker'], items: [['Construction: fixed price, date-certain', 0], ['Operating: availability and performance', 1], ['Demand or price, through a long-term PPA or concession', 2]], why: 'Lenders rely on project cash flows secured by contracts, with limited or no recourse to sponsors.' },
  { id: 'ad08b', topic: 'ADJ-08', kind: 'mcq', q: 'Cash available for debt service Rs. 120 crore, minimum DSCR 1.3x. What is the maximum annual debt service?', options: ['Rs. 92.3 crore', 'Rs. 156 crore', 'Rs. 120 crore', 'Rs. 84 crore'], answer: 0, why: '120 ÷ 1.3 = 92.3; multiply by the annuity factor to size the debt.', tags: [null, 'concept', 'concept', 'arithmetic'] },
];
